packages/shared/lib/components/ActiontechTable/hooks/useTableRequestParams.tsx, packages/shared/lib/styleWrapper/element.ts
1. add empty validation for CreateSortParams
2. supply ConsolidatedListStyleWrapper
=> [chore]: supply shared components

packages/base/src/hooks/useAuditRequired/index.tsx, packages/base/src/page/DataSource/DataSourceForm/index.tsx, packages/base/src/page/SyncDataSource/SyncTaskForm/SyncTaskForm.tsx, packages/base/src/page/SyncDataSource/SyncTaskForm/index.tsx, packages/base/src/page/SyncDataSource/SyncTaskList/column.tsx, packages/base/src/page/SyncDataSource/SyncTaskList/index.tsx, packages/base/src/page/SyncDataSource/index.tsx, packages/sqle/src/page/Whitelist/List/index.tsx, packages/sqle/src/page/Whitelist/index.tsx
related to [issue-1945](https://github.com/actiontech/sqle/issues/1945)，supply the same interaction in SyncTaskForm
=> [chore](SyncTask): supply AuditRequired and fix some styles problem

packages/shared/lib/components/CopyIcon/CopyIcon.test.tsx, packages/shared/lib/components/CopyIcon/CopyIcon.tsx, packages/sqle/src/page/Order/AuditDetail/DataSourceResultList/components/ResultCard.tsx
https://github.com/actiontech/sqle/issues/1972
=> [fix]: Resolve text formatting loss issue during copying process

packages/sqle/src/hooks/useDatabaseType/index.tsx, packages/sqle/src/page/Rule/index.tsx, packages/sqle/src/page/Rule/style.ts, packages/sqle/src/page/Rule/useRuleFilterForm.tsx
fix RuleList Page loading display problem and check all pages' loading status
=> [fix]:  fix RuleList Page loading display problem

packages/sqle/src/page/Order/SQLStatementForm/SQLStatementForm.tsx
fix: https://github.com/actiontech/sqle/issues/2013
=> [fix]:  The accept props of mybatis file upload is adjusted to .xml

packages/shared/lib/components/BasicDrawer/style.ts, packages/sqle/src/locale/en-US/order.ts, packages/sqle/src/locale/zh-CN/order.ts, packages/sqle/src/page/Order/SQLStatementForm/SQLStatementForm.tsx, packages/sqle/src/page/Order/SQLStatementForm/UploadType.tsx, packages/sqle/src/page/Order/SQLStatementForm/index.ts, packages/sqle/src/page/Order/SQLStatementForm/style.ts, packages/sqle/src/page/Order/hooks/useAuditOrder.tsx, packages/sqle/src/page/SqlAudit/Create/SQLStatementForm/index.tsx
- sql audit create upload type style
- global drawer closed icon style
- init upload file com when reset create order reset form
=> [feature](order create ): order upload support zip

packages/sqle/src/page/AuditPlan/PlanList/TableTaskTypeFilter/index.tsx
- tidy same mean task name data form api data 
- fix task type correlation between source type
=> [fix](audit plan): audit plan task and source type filter

packages/shared/lib/api/sqle/service/rule_template/index.d.ts, packages/sqle/src/page/Rule/index.tsx
feature: [DMS-647](http://10.186.18.11/jira/browse/DMS-647)
=> [feature](sqle/rule):update filter fuzzy name for rule list

packages/base/src/App.tsx, packages/shared/lib/components/ActiontechTable/hooks/useTableRequestParams.tsx, packages/shared/lib/components/BasicRangePicker/index.tsx, packages/sqle/src/components/ReportDrawer/index.tsx, packages/sqle/src/locale/zh-CN/sqlManagement.ts, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/column.tsx, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/hooks/useRuleTips.tsx, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/index.tsx
- add filter rule name for sql management
- fix table filter datepicker size
- fix global date picker local 'zh'
- fix ReportDrawer no showAnnotation params
=> [feature](sql management, sql com ReportDrawer, global datepicker): filter sql management

packages/sqle/src/page/ProjectManage/Overview/hooks/useChatsDataByAPI.ts
issue: [DMS-648](http://10.186.18.11/jira/browse/DMS-648)
=> [fix](project overview):delete first get data api

packages/base/src/page/DataSource/DataSourceList/index.tsx, packages/shared/lib/components/ActiontechTable/hooks/useTableRequestParams.tsx, packages/shared/lib/styles/tool.less, packages/sqle/src/page/OperationRecord/List/index.tsx, packages/sqle/src/page/Order/List/index.tsx, packages/sqle/src/page/SqlAudit/List/index.tsx, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/index.tsx
issue: [DMS-655](http://10.186.18.11/jira/browse/DMS-655)
=> [fix](reset page index): reset page index 1 when table filter info change 

packages/sqle/src/locale/en-US/sqlAudit.ts, packages/sqle/src/locale/zh-CN/sqlAudit.ts, packages/sqle/src/page/SqlAudit/Create/SQLInfoForm/index.type.ts, packages/sqle/src/page/SqlAudit/Create/SQLStatementForm/SqlUploadFileCont.tsx, packages/sqle/src/page/SqlAudit/Create/SQLStatementForm/index.tsx, packages/sqle/src/page/SqlAudit/Create/SQLStatementForm/index.type.ts
issue: [actiontech/sqle/issues/2119](https://github.com/actiontech/sqle/issues/2119)
=> [fix](sql audit create): api xml name for mybatisFile

packages/sqle/src/page/SqlAnalyze/AuditPlan/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlAnalyze/SqlAnalyze/style.ts
fix:https://github.com/actiontech/sqle/issues/2118
=> [fix](sql analyze): SQL statement wrap display

packages/base/src/page/DataSource/DataSourceList/index.tsx, packages/base/vite.config.ts, packages/shared/lib/components/ActiontechTable/hooks/useTableRequestParams.tsx, packages/sqle/src/page/AuditPlan/PlanList/index.tsx, packages/sqle/src/page/OperationRecord/List/index.tsx, packages/sqle/src/page/Order/List/index.tsx, packages/sqle/src/page/SqlAudit/List/index.tsx, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/index.tsx
jira: [DMS-719](http://10.186.18.11/jira/browse/DMS-719)
=> [fix](useTableRequestParams) page index 1 when filter text change

packages/sqle/src/page/Order/Create/SQLInfoForm/DatabaseInfo.tsx
fix: https://github.com/actiontech/sqle/issues/2127
=> [fix]: request data source parameters

packages/shared/lib/api/sqle/service/SqlManage/index.d.ts, packages/shared/lib/api/sqle/service/SqlManage/index.enum.ts, packages/shared/lib/api/sqle/service/SqlManage/index.ts, packages/shared/lib/api/sqle/service/common.d.ts, packages/sqle/src/locale/en-US/sqlManagement.ts, packages/sqle/src/locale/zh-CN/sqlManagement.ts, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/StatusFilter.tsx, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/column.tsx, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/hooks/useStaticStatus.ts, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/index.tsx
issue: https://github.com/actiontech/sqle-ee/issues/1229
=> [feature](sql management): add endpoint information

packages/sqle/src/page/SqlManagement/component/SQLEEIndex/Modal/StatusDrawer/index.tsx, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/column.tsx
同步需求：[sqle-ee/issues/1210](https://github.com/actiontech/sqle-ee/issues/1210)
jira: [DMS-764](http://10.186.18.11/jira/browse/DMS-764)
=> [fix]: sql management drawer

packages/base/src/page/CloudBeaver/__snapshots__/index.test.tsx.snap, packages/base/src/page/CloudBeaver/index.test.tsx, packages/base/src/page/CloudBeaver/index.tsx, packages/base/src/testUtils/mockApi/cloudBeaver/index.ts, packages/shared/lib/testUtil/mockApi.ts
[jira](http://10.186.18.11/jira/browse/DMS-745)
=> [test]:(base CloudBeaver) Add unit tests

packages/base/src/page/UserCenter/components/test/__snapshots__/PermissionList.test.tsx.snap, packages/base/src/page/UserCenter/components/test/__snapshots__/RoleList.test.tsx.snap, packages/base/src/page/UserCenter/components/test/__snapshots__/UserList.test.tsx.snap, packages/shared/lib/components/ActiontechTable/Table.tsx, packages/shared/lib/components/ActiontechTable/__snapshots__/index.test.tsx.snap, packages/shared/lib/components/ActiontechTable/index.test.tsx, packages/shared/lib/components/ActiontechTable/style.tsx, packages/shared/lib/components/ActiontechTable/utils/index.test.tsx, packages/shared/lib/components/ActiontechTable/utils/index.ts, packages/shared/lib/components/BasicTable/__snapshots__/index.test.tsx.snap, packages/shared/lib/styleWrapper/element.ts, packages/sqle/src/page/SqlAnalyze/AuditPlan/__snapshots__/index.test.tsx.snap
[jira](http://10.186.18.11/jira/browse/DMS-773)
=> [chore]: Restore "ConsolidatedListStyleWrapper"

packages/base/src/page/BindUser/__snapshots__/index.ce.test.tsx.snap, packages/base/src/page/BindUser/__snapshots__/index.test.tsx.snap, packages/base/src/page/BindUser/index.ce.test.tsx, packages/base/src/page/BindUser/index.test.tsx, packages/base/src/page/BindUser/index.tsx
jira: [DMS-744](http://10.186.18.11/jira/browse/DMS-744)
=> [test](base/bind user):add unit test

jest.config.js, packages/base/src/hooks/useSessionUser/index.test.tsx, packages/base/src/hooks/useSqlReviewTemplateToggle/index.test.tsx, packages/base/src/hooks/useSqlReviewTemplateToggle/index.tsx, packages/base/src/hooks/useSystemConfig.tsx/__snapshots__/index.test.tsx.snap, packages/base/src/hooks/useSystemConfig.tsx/index.test.tsx, packages/base/src/hooks/useSystemConfig.tsx/index.tsx, packages/base/src/hooks/useThemeStyleData/__snapshots__/index.test.tsx.snap, packages/base/src/hooks/useThemeStyleData/index.test.tsx, packages/base/src/hooks/useThemeStyleData/index.ts, packages/base/src/page/DataSource/DataSourceForm/index.tsx, packages/base/src/page/SyncDataSource/SyncTaskForm/SyncTaskForm.tsx, packages/shared/lib/testUtil/mockHook/data.ts, packages/shared/lib/testUtil/mockHook/mockUseCurrentUser.ts
[jira](http://10.186.18.11/jira/browse/DMS-742)
=> [test]:(Base/hooks) Add unit tests

packages/base/src/page/UserCenter/components/test/__snapshots__/RoleList.test.tsx.snap, packages/base/src/page/UserCenter/components/test/__snapshots__/UserList.test.tsx.snap, packages/shared/lib/api/sqle/service/SqlManage/index.d.ts, packages/shared/lib/api/sqle/service/SqlManage/index.ts, packages/shared/lib/api/sqle/service/audit_plan/index.d.ts, packages/shared/lib/api/sqle/service/audit_plan/index.ts, packages/shared/lib/api/sqle/service/common.d.ts, packages/shared/lib/components/ActiontechTable/hooks/test/__snapshots__/useTableAction.test.tsx.snap, packages/shared/lib/components/ActiontechTable/hooks/useTableAction.tsx, packages/sqle/src/components/RenderSQL/index.tsx, packages/sqle/src/locale/zh-CN/sqlManagement.ts, packages/sqle/src/page/AuditPlan/index.tsx, packages/sqle/src/page/SqlAnalyze/SqlManage/index.tsx, packages/sqle/src/page/SqlAnalyze/SqlManage/index.type.ts, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/column.tsx, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/index.tsx, packages/sqle/src/router/config.tsx
https://github.com/actiontech/sqle-ee/issues/1271
https://github.com/actiontech/sqle-ee/issues/1266
=> [feature]:(SQLManage) Sync SQL analyze feature

packages/sqle/src/page/Order/Create/index.tsx, packages/sqle/src/page/Order/SQLStatementForm/UploadType.tsx
https://github.com/actiontech/sqle/issues/2205
=> [chore]:(Order) Hide MyBatis SQL statement upload method

packages/shared/lib/testUtil/common.tsx, packages/sqle/src/page/AuditPlan/PlanDetail/DetailCom/style.ts, packages/sqle/src/page/SqlAnalyze/AuditPlan/index.test.tsx, packages/sqle/src/page/SqlAnalyze/Order/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlAnalyze/Order/index.test.tsx, packages/sqle/src/page/SqlAnalyze/Order/index.tsx, packages/sqle/src/page/SqlAnalyze/SqlAnalyze/test/SqlAnalyze.test.tsx, packages/sqle/src/page/SqlAnalyze/SqlAnalyze/test/__snapshots__/SqlAnalyze.test.tsx.snap, packages/sqle/src/page/SqlAnalyze/SqlAnalyze/test/__snapshots__/useSQLExecPlan.test.tsx.snap, packages/sqle/src/page/SqlAnalyze/SqlAnalyze/test/__snapshots__/useTableSchema.test.tsx.snap, packages/sqle/src/page/SqlAnalyze/SqlAnalyze/test/useSQLExecPlan.test.tsx, packages/sqle/src/page/SqlAnalyze/SqlAnalyze/test/useTableSchema.test.tsx, packages/sqle/src/page/SqlAnalyze/SqlAnalyze/useSQLExecPlan.tsx, packages/sqle/src/page/SqlAnalyze/SqlAnalyze/useTableSchema.tsx, packages/sqle/src/page/SqlAnalyze/SqlManage/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlAnalyze/SqlManage/index.test.tsx, packages/sqle/src/page/SqlAnalyze/SqlManage/index.tsx, packages/sqle/src/page/SqlAnalyze/__testData__/index.ts, packages/sqle/src/testUtils/customRender.tsx
jira: [DMS-790](http://10.186.18.11/jira/browse/DMS-790)
=> [test](sqle/SqlAnalyze): unit test

packages/shared/lib/Icon/common.tsx, packages/shared/lib/api/sqle/service/common.d.ts, packages/sqle/src/components/ReportDrawer/index.tsx, packages/sqle/src/components/ReportDrawer/index.type.ts, packages/sqle/src/components/ReportDrawer/style.ts, packages/sqle/src/locale/en-US/auditPlan.ts, packages/sqle/src/locale/zh-CN/auditPlan.ts, packages/sqle/src/page/Order/Common/AuditResultList/List/AuditResultDrawer.tsx
issue: https://github.com/actiontech/sqle/issues/2222
=> [feature](SqlAudit/Order): sql start line

packages/base/src/page/DataExportManagement/List/column.tsx, packages/shared/lib/api/base/service/dms/index.d.ts
https://github.com/actiontech/dms-ee/issues/112
=> [chore]:(Data Export) update list filter param name

packages/base/src/locale/en-US/dmsMenu.ts, packages/base/src/locale/zh-CN/dmsMenu.ts, packages/base/src/page/Nav/Copyright/index.tsx, packages/base/src/page/Nav/index.tsx, packages/shared/lib/styleWrapper/nav.ts, packages/sqle/src/components/RuleDetail/__snapshots__/index.test.tsx.snap, packages/sqle/src/components/RuleDetail/index.tsx, packages/sqle/src/components/RuleList/RuleList.tsx, packages/sqle/src/components/RuleList/style.ts, packages/sqle/src/page/Rule/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/Rule/index.tsx, packages/sqle/src/page/RuleTemplate/RuleTemplateForm/RuleSelect/index.tsx
fix:https://github.com/actiontech/dms/issues/139?open_in_browser=true
jira:http://10.186.18.11/jira/browse/DMS-806
=> [feature](base/Nav): add copyright information

Makefile, packages/base/src/page/DataExportManagement/List/__tests__/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataExportManagement/List/__tests__/index.test.tsx, packages/base/src/page/DataExportManagement/List/index.tsx, packages/base/src/page/DataExportManagement/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/base/src/page/DataExportManagement/__tests__/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataExportManagement/__tests__/index.ce.test.tsx, packages/base/src/page/DataExportManagement/__tests__/index.test.tsx, packages/base/src/testUtils/mockApi/dataExport/data.ts, packages/base/src/testUtils/mockApi/dataExport/index.ts, packages/base/vite.config.ts
[jira](http://10.186.18.11/jira/browse/DMS-830)
=> [test]:(Data Export List) add test units

packages/shared/lib/components/EnterpriseFeatureDisplay/__snapshots__/ce.test.tsx.snap, packages/shared/lib/components/EnterpriseFeatureDisplay/index.data.ts, packages/sqle/src/page/OperationRecord/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/ReportStatistics/__snapshots__/ce.test.tsx.snap, packages/sqle/src/page/SqlManagement/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/Whitelist/__snapshots__/ce.test.tsx.snap
fix:https://github.com/actiontech/dms/issues/152
=> [fix](shared/EnterpriseFeatureDisplay): link url

packages/base/src/page/SyncDataSource/__snapshots__/index.ce.test.tsx.snap, packages/base/src/page/SyncDataSource/__snapshots__/index.test.tsx.snap, packages/base/src/page/SyncDataSource/index.ce.test.tsx, packages/base/src/page/SyncDataSource/index.test.tsx, packages/base/src/page/System/GlobalSetting/__snapshots__/index.test.tsx.snap, packages/base/src/page/System/GlobalSetting/index.test.tsx, packages/base/src/page/System/License/__snapshots__/index.test.tsx.snap, packages/base/src/page/System/License/index.test.tsx, packages/base/src/page/System/ProcessConnection/DingTalkSetting/__snapshots__/index.test.tsx.snap, packages/base/src/page/System/ProcessConnection/DingTalkSetting/index.test.tsx, packages/base/src/page/System/ProcessConnection/LarkAuditSetting/components/ConfigExtraButtons.test.tsx, packages/base/src/page/System/ProcessConnection/LarkAuditSetting/components/ConfigExtraButtons.tsx, packages/base/src/page/System/ProcessConnection/LarkAuditSetting/components/__snapshots__/ConfigExtraButtons.test.tsx.snap, packages/base/src/page/System/PushNotification/LarkSetting/conponents/ConfigExtraButtons.test.tsx, packages/base/src/page/System/PushNotification/LarkSetting/conponents/__snapshots__/ConfigExtraButtons.test.tsx.snap, packages/base/src/page/System/PushNotification/SMTPSetting/components/ConfigExtraButtons.test.tsx, packages/base/src/page/System/PushNotification/SMTPSetting/components/__snapshots__/ConfigExtraButtons.test.tsx.snap, packages/base/src/page/System/PushNotification/WebhookSetting/index.test.tsx, packages/base/src/page/System/PushNotification/Wechat/components/ConfigExtraButtons.test.tsx, packages/base/src/page/System/PushNotification/Wechat/components/__snapshots__/ConfigExtraButtons.test.tsx.snap, packages/base/src/store/user/index.test.ts, packages/base/src/testUtils/mockApi/system/index.ts, packages/base/vite.config.ts
jira: http://10.186.18.11/jira/browse/DMS-838
=> [feature](unit test apended): base/system & store/user

packages/shared/lib/api/base/service/common.d.ts, packages/shared/lib/api/base/service/common.enum.ts, packages/shared/lib/api/base/service/dms/index.d.ts, packages/shared/lib/api/base/service/dms/index.ts, packages/sqle/src/page/ReportStatistics/EEIndex/component/charts/LicenseStatistics/index.tsx, packages/sqle/src/testUtils/mockApi/statistic/data.ts, packages/sqle/src/testUtils/mockApi/statistic/index.ts
https://github.com/actiontech/dms-ee/issues/170
=> [feature]: update license usage api

packages/base/src/page/SyncDataSource/__snapshots__/index.ce.test.tsx.snap
http://10.186.18.11/jira/browse/DMS-843
=> [fix](SyncDataSource): ce test case

packages/base/src/page/SyncDataSource/__snapshots__/index.ce.test.tsx.snap, packages/shared/lib/components/ActiontechTable/components/test/ColumnsSetting.test.tsx, packages/shared/lib/components/ActiontechTable/components/test/__snapshots__/ColumnsSetting.test.tsx.snap, packages/shared/lib/components/ActiontechTable/components/test/mockHooks/data.ts, packages/shared/lib/components/ActiontechTable/components/test/mockHooks/mockUseTableSettings.ts
issue: [DMS-838](http://10.186.18.11/jira/browse/DMS-838)
=> [test](shared/ActiontechTable/ColumnsSetting):case ColumnsSetting

packages/sqle/src/page/ReportStatistics/EEIndex/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/ReportStatistics/EEIndex/index.test.tsx, packages/sqle/src/page/ReportStatistics/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/ReportStatistics/index.test.tsx
=> [fix](ReportStatistics): fix report statistics snap date error

packages/shared/lib/hooks/useNotificationContext/__snapshots__/index.test.tsx.snap, packages/shared/lib/hooks/useNotificationContext/index.test.tsx
[jira](http://10.186.18.11/jira/browse/DMS-847)
=> [test]:(useNotificationContext)  Supplementary testing coverage

packages/sqle/src/page/ProjectOverview/component/DataSourceCount/ToolTipCustomContent.tsx, packages/sqle/src/page/ProjectOverview/component/DataSourceCount/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/ProjectOverview/component/DataSourceCount/index.data.ts, packages/sqle/src/page/ProjectOverview/component/DataSourceCount/index.enum.ts, packages/sqle/src/page/ProjectOverview/component/DataSourceCount/index.test.tsx, packages/sqle/src/page/ProjectOverview/component/DataSourceCount/index.tsx, packages/sqle/src/page/ProjectOverview/component/DataSourceCount/index.type.ts, packages/sqle/src/page/ProjectOverview/component/ScanTask/charts/TaskList/BarChat.tsx, packages/sqle/src/page/ProjectOverview/component/ScanTask/charts/TaskList/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/ProjectOverview/component/ScanTask/charts/TaskList/index.data.tsx, packages/sqle/src/page/ProjectOverview/component/ScanTask/charts/TaskList/index.test.tsx, packages/sqle/src/page/ProjectOverview/component/ScanTask/index.tsx, packages/sqle/src/testUtils/mockApi/projectOverview/data.ts
[jira](http://10.186.18.11/jira/browse/DMS-848)
=> [test]:(ProjectOverview) Supplementary testing coverage

jest.config.js, packages/base/src/page/Nav/SideMenu/ProjectSelector/__tests__/__snapshots__/index.test.tsx.snap, packages/base/src/page/Nav/SideMenu/ProjectSelector/__tests__/index.test.tsx
[jira](http://10.186.18.11/jira/browse/DMS-845)
=> [test]:(ProjectSelector) Supplementary testing coverage

packages/base/package.json
fix: https://github.com/actiontech/sqle/issues/2291
=> [chore]: Demo edition changes [skip ci]

packages/sqle/src/page/ProjectOverview/component/DataSourceCount/index.tsx
fix: https://github.com/actiontech/sqle/issues/2293
=> [fix]:(Project Overview) Restore lost legend name

packages/base/src/hooks/useSystemConfig/index.test.tsx, packages/base/src/locale/zh-CN/dmsSystem.ts, packages/base/src/page/DataExportManagement/Create/components/SubmitWorkflow/__tests__/index.test.tsx, packages/base/src/page/DataExportManagement/Create/hooks/__tests__/index.redux.test.ts, packages/base/src/page/DataExportManagement/Detail/hooks/__tests__/index.redux.test.ts, packages/base/src/page/DataExportManagement/Detail/hooks/__tests__/useInitDataWithRequest.test.ts, packages/base/src/page/DataSource/components/List/index.test.tsx, packages/base/src/page/Nav/SideMenu/MenuList/index.test.tsx, packages/base/src/page/Nav/SideMenu/UserMenu/Modal/CompanyNoticeModal/index.test.tsx, packages/base/src/page/Nav/SideMenu/__tests__/index.test.tsx, packages/base/src/page/Nav/SideMenu/__tests__/useRecentlyOpenedProjects.test.ts, packages/base/src/page/Project/List/index.test.tsx, packages/base/src/page/System/LoginConnection/Oauth/__snapshots__/index.test.tsx.snap, packages/base/src/page/System/LoginConnection/Oauth/components/ConfigField.tsx, packages/base/src/page/System/LoginConnection/Oauth/components/__snapshots__/ConfigField.test.tsx.snap, packages/base/src/page/System/LoginConnection/Oauth/index.test.tsx, packages/base/src/page/System/LoginConnection/Oauth/index.tsx, packages/base/src/page/System/LoginConnection/Oauth/index.type.ts, packages/base/src/page/System/LoginConnection/__snapshots__/index.test.tsx.snap, packages/base/src/testUtils/mockApi/system/data.ts, packages/shared/lib/api/base/service/common.d.ts, packages/shared/lib/api/common/authInvalid/index.test.tsx, packages/shared/lib/global/useUserInfo/index.test.tsx, packages/sqle/src/components/RuleDetail/index.test.tsx, packages/sqle/src/page/Order/AuditDetail/index.test.tsx, packages/sqle/src/page/Order/List/index.ce.test.tsx, packages/sqle/src/page/Order/List/index.test.tsx
https://github.com/actiontech/dms-ee/issues/190
=> [feature]:Add skip check state switch and replace nthCalledWith with toHaveBeenNthCalledWith

.gitignore, package.json, pnpm-lock.yaml, scripts/jest/merge-report-json.js, scripts/jest/run-ci-ce.sh, scripts/jest/run-ci-ee.sh
=> [test]: Update merging method for multiple test reports

packages/sqle/src/components/RuleDetail/__snapshots__/index.test.tsx.snap
=> [test]: update snapshot

packages/base/src/locale/en-US/dmsSyncDataSource.ts, packages/base/src/locale/zh-CN/dmsSyncDataSource.ts, packages/base/src/page/SyncDataSource/AddPage/__snapshots__/index.test.tsx.snap, packages/base/src/page/SyncDataSource/Form/__snapshots__/index.test.tsx.snap, packages/base/src/page/SyncDataSource/List/__snapshots__/index.test.tsx.snap, packages/base/src/page/SyncDataSource/List/index.tsx, packages/base/src/page/SyncDataSource/UpdatePage/__snapshots__/index.test.tsx.snap, packages/sqle/src/components/RuleDetail/__snapshots__/index.test.tsx.snap
fix: https://github.com/actiontech/dms-ee/issues/183
=> [fix](SyncDataSource): Permissions and name changes

.github/actions/catch-install-pnpm/action.yml, .github/workflows/main.yml
assign in @Rain-1214 
更新部分 actions 版本，添加 delete artifact 步骤
=> [chore]:(github action) add step to delete artifact

packages/base/src/locale/zh-CN/dmsDataExport.ts, packages/base/src/page/DataExportManagement/Detail/__tests__/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataExportManagement/Detail/components/ExportDetail/__tests__/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataExportManagement/Detail/components/ExportDetail/__tests__/index.test.tsx, packages/base/src/page/DataExportManagement/Detail/components/ExportDetail/index.tsx, packages/base/src/testUtils/mockApi/dataExport/index.ts, packages/base/vite.config.ts, packages/shared/lib/api/base/service/common.d.ts, packages/shared/lib/api/base/service/dms/index.d.ts, packages/shared/lib/api/base/service/dms/index.ts
https://github.com/actiontech/dms-ee/issues/211
=> [feature]:(Data Export) Support download sqls

package.json, packages/base/src/page/System/License/__snapshots__/index.test.tsx.snap, packages/base/src/page/System/License/index.test.tsx, packages/base/src/page/System/License/index.tsx, packages/shared/lib/api/common/ApiBase/index.ts, packages/shared/lib/components/ActiontechTable/hooks/useTableRequestError.tsx, packages/shared/lib/utils/Common.ts, packages/shared/lib/utils/__tests__/Common.test.ts, pnpm-lock.yaml
fix:https://github.com/actiontech/dms-ee/issues/203
=> [feature](System/License): add QR code and Blob type error message

packages/shared/lib/api/base/service/common.d.ts, packages/shared/lib/api/base/service/dms/index.d.ts, packages/shared/lib/api/base/service/dms/index.ts, packages/shared/lib/locale/en-US/common.ts, packages/shared/lib/locale/zh-CN/common.ts
=> [feature]: add data mask api and locale

packages/base/src/locale/en-US/dmsDataSource.ts, packages/base/src/locale/zh-CN/dmsDataSource.ts, packages/base/src/page/DataSource/components/AddDataSource/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataSource/components/AddDataSource/index.test.tsx, packages/base/src/page/DataSource/components/AddDataSource/index.tsx, packages/base/src/page/DataSource/components/Form/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataSource/components/Form/index.test.tsx, packages/base/src/page/DataSource/components/Form/index.tsx, packages/base/src/page/DataSource/components/Form/index.type.ts, packages/base/src/page/DataSource/components/List/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataSource/components/List/columns.tsx, packages/base/src/page/DataSource/components/List/index.test.tsx, packages/base/src/page/DataSource/components/List/index.tsx, packages/base/src/page/DataSource/components/UpdateDataSource/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataSource/components/UpdateDataSource/index.test.tsx, packages/base/src/page/DataSource/components/UpdateDataSource/index.tsx, packages/base/src/testUtils/mockApi/global/data.ts, scripts/jest/custom-transform.js
=> [feature](DataSource): sync data source change from dms-ui-ee about data mask

packages/base/src/__snapshots__/App.test.tsx.snap, packages/base/src/page/Home/DefaultScene/components/StepItems/__tests__/index.test.tsx, packages/base/src/page/Home/DefaultScene/components/StepItems/base.tsx, packages/base/src/page/Login/index.test.tsx, packages/base/src/page/Login/index.tsx, packages/base/src/page/Nav/SideMenu/MenuList/__snapshots__/index.test.tsx.snap, packages/base/src/page/Nav/SideMenu/MenuList/index.test.tsx, packages/base/src/page/Nav/SideMenu/MenuList/menus/base.tsx, packages/base/src/page/Nav/SideMenu/UserMenu/components/GlobalSetting.tsx, packages/base/src/page/Nav/SideMenu/UserMenu/components/test/GlobalSetting.test.tsx, packages/base/src/page/Nav/SideMenu/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/base/src/page/Nav/SideMenu/__tests__/__snapshots__/index.test.tsx.snap, packages/base/src/page/SyncDataSource/AddPage/__snapshots__/index.test.tsx.snap, packages/base/src/page/SyncDataSource/AddPage/index.test.tsx, packages/base/src/page/SyncDataSource/AddPage/index.tsx, packages/base/src/page/SyncDataSource/List/__snapshots__/index.test.tsx.snap, packages/base/src/page/SyncDataSource/List/column.tsx, packages/base/src/page/SyncDataSource/List/index.test.tsx, packages/base/src/page/SyncDataSource/List/index.tsx, packages/base/src/page/SyncDataSource/UpdatePage/__snapshots__/index.test.tsx.snap, packages/base/src/page/SyncDataSource/UpdatePage/index.test.tsx, packages/base/src/page/SyncDataSource/UpdatePage/index.tsx, packages/base/src/router/router.base.tsx, packages/base/src/router/test/__snapshots__/router.base.test.tsx.snap, packages/base/src/router/test/__snapshots__/router.ce.base.test.tsx.snap, packages/base/src/router/test/__snapshots__/router.ce.sqle.test.tsx.snap, packages/base/src/router/test/__snapshots__/router.sqle.test.tsx.snap, packages/base/src/router/test/router.base.test.tsx, packages/base/src/router/test/router.ce.base.test.tsx
[jira](http://10.186.18.11/jira/projects/DMS/issues/DMS-854?filter=allopenissues)
=> [chore](base): Modify route name format

packages/base/src/page/Account/__snapshots__/index.test.tsx.snap, packages/base/src/page/Account/components/AccessToken/GenerateTokenModal.tsx, packages/base/src/page/Account/components/AccessToken/__tests__/__snapshots__/index.test.tsx.snap, packages/base/src/page/Account/components/AccessToken/style.ts
https://github.com/actiontech/sqle/issues/2309
=> [style]: (Access Token) adjust style

packages/sqle/src/page/Order/Common/DownloadRecord/index.test.tsx, packages/sqle/src/page/Order/Common/DownloadRecord/index.tsx
https://github.com/actiontech/sqle-ee/issues/1404
=> [fix]: Add responseType parameter to download

packages/shared/lib/components/TokenCom/__snapshots__/index.test.tsx.snap, packages/shared/lib/components/TokenCom/index.test.tsx
=> [test](shared/TokenCom): Supplementary unit testing

packages/base/src/page/Member/List/MemberGroupList.tsx, packages/base/src/page/Member/List/MemberList.tsx, packages/shared/lib/hooks/useChangeTheme/index.test.tsx, packages/sqle/src/page/ProjectOverview/component/ScanTask/charts/TaskList/index.tsx
=> [chore]: fix ci warning

packages/base/src/__snapshots__/App.test.tsx.snap, packages/shared/lib/styleWrapper/nav.ts, packages/sqle/src/page/AuditPlan/PlanDetail/DetailReport/index.tsx
fix:https://github.com/actiontech/sqle/issues/2322
=> [fix](Copyright&AuditPlan): Copyright style&AuditPlan analyze button

packages/shared/lib/api/sqle/service/common.d.ts, packages/shared/lib/api/sqle/service/common.enum.ts, packages/shared/lib/api/sqle/service/configuration/index.d.ts, packages/shared/lib/api/sqle/service/configuration/index.ts, packages/shared/lib/api/sqle/service/task/index.d.ts, packages/shared/lib/api/sqle/service/task/index.ts, packages/sqle/src/page/AuditPlan/PlanList/column.tsx, packages/sqle/src/page/AuditPlan/PlanList/index.tsx
https://github.com/actiontech/sqle/issues/2340
=> [chore]: build api and adjust operation column permissions

packages/base/src/page/DataSource/components/AddDataSource/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataSource/components/AddDataSource/index.test.tsx, packages/base/src/page/DataSource/components/Form/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataSource/components/Form/index.tsx, packages/base/src/page/DataSource/components/UpdateDataSource/__snapshots__/index.test.tsx.snap
=> [feature](base/DataSource): sync router modification from dms-ui-ee

packages/sqle/src/locale/zh-CN/audit.ts, packages/sqle/src/page/Order/AuditDetail/DataSourceResultList/__snapshots__/WaterfallList.test.tsx.snap, packages/sqle/src/page/Order/AuditDetail/DataSourceResultList/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/Order/AuditDetail/DataSourceResultList/components/ResultCard.tsx, packages/sqle/src/page/Order/AuditDetail/DataSourceResultList/components/test/__snapshots__/ResultCard.ce.test.tsx.snap, packages/sqle/src/page/Order/AuditDetail/DataSourceResultList/components/test/__snapshots__/ResultCard.test.tsx.snap, packages/sqle/src/page/Order/AuditDetail/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/Order/AuditDetail/style.ts
https://github.com/actiontech/sqle/issues/2352
=> [feature]: (Order) Add SQL statement file location information

packages/sqle/src/page/Order/AuditDetail/DataSourceResultList/components/AuditResultTree.tsx, packages/sqle/src/page/Order/AuditDetail/DataSourceResultList/components/test/AuditResultTree.test.tsx, packages/sqle/src/page/Order/AuditDetail/DataSourceResultList/components/test/__snapshots__/AuditResultTree.test.tsx.snap
fix: https://github.com/actiontech/sqle/issues/2325
=> [fix]:(Order/AuditDetail/AuditResultTree) Handle audit results with empty rule_name

packages/base/src/__snapshots__/App.test.tsx.snap, packages/base/src/index.less, packages/base/src/page/Nav/SideMenu/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/base/src/page/Nav/SideMenu/__tests__/__snapshots__/index.test.tsx.snap, packages/shared/lib/styleWrapper/nav.ts, packages/shared/lib/styles/_variable.less
fix:https://github.com/actiontech/dms/issues/241
=> [style](global): scrollbar style on Windows

packages/shared/lib/api/sqle/service/common.enum.ts, packages/shared/lib/components/ToggleTokens/__snapshots__/index.test.tsx.snap, packages/shared/lib/components/ToggleTokens/index.test.tsx, packages/shared/lib/components/ToggleTokens/index.tsx, packages/shared/lib/components/ToggleTokens/index.type.ts, packages/shared/lib/components/ToggleTokens/style.ts, packages/shared/lib/index.ts, packages/sqle/src/locale/zh-CN/order.ts, packages/sqle/src/page/Order/AuditDetail/ScheduleTimeModal/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/Order/AuditDetail/ScheduleTimeModal/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/Order/AuditDetail/ScheduleTimeModal/components/ConfirmationSettingForm.tsx, packages/sqle/src/page/Order/AuditDetail/ScheduleTimeModal/components/__tests__/ConfirmationSettingForm.test.tsx, packages/sqle/src/page/Order/AuditDetail/ScheduleTimeModal/components/__tests__/__snapshots__/ConfirmationSettingForm.test.tsx.snap, packages/sqle/src/page/Order/AuditDetail/ScheduleTimeModal/components/index.type.ts, packages/sqle/src/page/Order/AuditDetail/ScheduleTimeModal/components/style.ts, packages/sqle/src/page/Order/AuditDetail/ScheduleTimeModal/index.test.tsx, packages/sqle/src/page/Order/AuditDetail/ScheduleTimeModal/index.tsx, packages/sqle/src/page/Order/AuditDetail/ScheduleTimeModal/index.type.ts, packages/sqle/src/testUtils/mockApi/configuration/index.ts
可以先复审，还要等后端的 api 定义以及联调
https://github.com/actiontech/sqle-ee/issues/1473
=> [feature]: Add ToggleTokens public component and support for scheduled confirmations in Feishu approval workflows

packages/base/src/hooks/useProjectTips/index.ce.test.tsx, packages/base/src/hooks/useProjectTips/index.ts
=> [fix](DataSource): Do not call project tips api in CE Edition

packages/sqle/src/page/Order/AuditDetail/index.tsx, packages/sqle/src/page/Order/Common/DownloadRecord/index.test.tsx
fix:https://github.com/actiontech/sqle/issues/2371
=> [fix](Order): duplicate parameter error

packages/sqle/src/page/Order/Create/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/Order/Create/index.test.tsx, packages/sqle/src/page/Order/Create/index.tsx
fix: https://github.com/actiontech/sqle/issues/2382
=> [chore]: Added validation checks for base info fields and optimize unit testing

packages/shared/lib/api/sqle/service/common.d.ts, packages/shared/lib/api/sqle/service/common.enum.ts, packages/shared/lib/api/sqle/service/sql_optimization/index.d.ts, packages/shared/lib/api/sqle/service/sql_optimization/index.ts, packages/shared/lib/api/sqle/service/system/index.d.ts, packages/shared/lib/api/sqle/service/system/index.enum.ts, packages/shared/lib/api/sqle/service/system/index.ts, packages/shared/lib/api/sqle/service/workflow/index.d.ts, packages/shared/lib/api/sqle/service/workflow/index.ts, packages/sqle/src/page/Order/AuditDetail/ScheduleTimeModal/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/Order/AuditDetail/ScheduleTimeModal/components/ConfirmationSettingForm.tsx, packages/sqle/src/page/Order/AuditDetail/ScheduleTimeModal/components/__tests__/ConfirmationSettingForm.test.tsx, packages/sqle/src/page/Order/AuditDetail/ScheduleTimeModal/components/__tests__/__snapshots__/ConfirmationSettingForm.test.tsx.snap, packages/sqle/src/page/Order/AuditDetail/ScheduleTimeModal/index.test.tsx, packages/sqle/src/testUtils/mockApi/order/index.ts
https://github.com/actiontech/sqle-ee/issues/1480
=> [feature]:(ScheduleTimeModal) build api and set default confirmation method

packages/shared/lib/api/sqle/service/common.d.ts, packages/shared/lib/api/sqle/service/common.enum.ts, packages/shared/lib/api/sqle/service/task/index.d.ts
https://github.com/actiontech/sqle-ee/issues/1468
api 生成
=> [chore]: build api

packages/sqle/src/locale/zh-CN/sqlOptimization.ts, packages/sqle/src/page/SqlOptimization/Detail/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlOptimization/Detail/index.tsx, packages/sqle/src/page/SqlOptimization/Overview/OptimizationSqlList/columns.tsx, packages/sqle/src/page/SqlOptimization/Overview/OptimizationSqlList/index.tsx, packages/sqle/src/page/SqlOptimization/Overview/__snapshots__/index.test.tsx.snap
issue:https://github.com/actiontech/sqle-ee/issues/1422
修改概览sql语句列表序号和详情规则sql字段
=> [fix](SqlOptimization): SQL statement list numbering and rule SQL

packages/shared/lib/components/ModeSwitcher/index.type.ts, packages/sqle/src/data/EmitterKey.ts, packages/sqle/src/page/Order/AuditDetail/index.tsx, packages/sqle/src/page/Order/Create/SQLInfoForm/__tests__/__snapshots__/SQLInfoFormItem.test.tsx.snap, packages/sqle/src/page/Order/Detail/ModifySQL/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/Order/Detail/ModifySQL/index.test.tsx, packages/sqle/src/page/Order/Detail/ModifySQL/index.tsx, packages/sqle/src/page/Order/Detail/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/Order/SQLStatementForm/SQLStatementForm.tsx, packages/sqle/src/page/Order/SQLStatementForm/SQLStatementFormTabs.tsx, packages/sqle/src/page/Order/SQLStatementForm/__tests__/SQLStatementForm.test.tsx, packages/sqle/src/page/Order/SQLStatementForm/__tests__/__snapshots__/SQLStatementForm.test.tsx.snap, packages/sqle/src/page/Order/SQLStatementForm/__tests__/__snapshots__/SQLStatementFormTabs.test.tsx.snap, packages/sqle/src/page/Order/SQLStatementForm/index.ts
https://github.com/actiontech/sqle-ee/issues/1468
限制驳回工单后修改SQL时必须为提交时的SQL输入类型
=> [feature]:(Order) Enforce SQL type consistency upon workflow rejection and modification

packages/sqle/src/page/Order/Create/EditSQLInfoDrawer/index.test.tsx, packages/sqle/src/page/Order/Create/SQLInfoForm/DatabaseInfo.tsx, packages/sqle/src/page/Order/Create/SQLInfoForm/SQLInfoFormItem.tsx, packages/sqle/src/page/Order/Create/SQLInfoForm/__tests__/DatabaseInfo.ce.test.tsx, packages/sqle/src/page/Order/Create/SQLInfoForm/__tests__/DatabaseInfo.test.tsx, packages/sqle/src/page/Order/Create/SQLInfoForm/__tests__/SQLInfoFormItem.test.tsx, packages/sqle/src/page/Order/Create/SQLInfoForm/__tests__/__snapshots__/SQLInfoFormItem.test.tsx.snap, packages/sqle/src/page/Order/Create/SQLInfoForm/__tests__/index.test.tsx, packages/sqle/src/page/Order/Create/SQLInfoForm/index.type.ts, packages/sqle/src/page/Order/Create/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/Order/Create/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/Order/Create/hooks/useCreateOrderFormState.ts, packages/sqle/src/page/Order/Create/index.type.ts, packages/sqle/src/page/Order/Detail/ModifySQL/index.tsx, packages/sqle/src/page/Order/SQLStatementForm/SQLStatementForm.tsx, packages/sqle/src/page/Order/SQLStatementForm/SQLStatementFormTabs.tsx, packages/sqle/src/page/Order/SQLStatementForm/__tests__/SQLStatementForm.test.tsx, packages/sqle/src/page/Order/SQLStatementForm/__tests__/SQLStatementFormTabs.test.tsx, packages/sqle/src/page/Order/SQLStatementForm/__tests__/__snapshots__/SQLStatementForm.test.tsx.snap, packages/sqle/src/page/Order/SQLStatementForm/__tests__/__snapshots__/SQLStatementFormTabs.test.tsx.snap, packages/sqle/src/page/Order/SQLStatementForm/index.ts
https://github.com/actiontech/sqle-ee/issues/1468
处理不同 sql 模式下当前sql来源错误的问题
优先级：高
这里暂时先不补充单元测试了，马上全部改掉。。
=> [fix]: Resolve incorrect SQL source attribution in varying SQL modes

packages/sqle/src/locale/zh-CN/sqlOptimization.ts, packages/sqle/src/page/SqlOptimization/Overview/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlOptimization/Overview/index.tsx
https://github.com/actiontech/sqle-ee/issues/1422
优先级：高
=> [chore]:(SqlOptimization) Add icon with tooltip to title

packages/sqle/src/page/SqlOptimization/Overview/OptimizationSqlList/columns.tsx, packages/sqle/src/page/SqlOptimization/Overview/OptimizationSqlList/index.tsx, packages/sqle/src/page/SqlOptimization/Overview/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlOptimization/Overview/index.tsx
issue:https://github.com/actiontech/sqle-ee/issues/1551
=> [fix](sqle/SqlOptimization): Hide details button when optimization fails

packages/sqle/src/page/PluginAudit/List/index.test.tsx, packages/sqle/src/page/SqlOptimization/List/index.test.tsx
=> [test]: fix unit testing errors

packages/base/src/page/Member/List/MemberList.tsx, packages/base/src/page/Member/List/column.tsx, packages/base/src/page/Member/List/test/__snapshots__/MemberGroupList.test.tsx.snap, packages/base/src/page/Member/List/test/__snapshots__/MemberList.test.tsx.snap, packages/base/src/page/Member/__snapshots__/index.test.tsx.snap, packages/base/src/page/Member/style.ts, packages/sqle/src/page/Home/CommonTable/column.tsx, packages/sqle/src/page/Home/DBAPanel/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/Home/DEVPanel/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/Home/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/RuleTemplate/RuleTemplateList/CommonTable/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/RuleTemplate/RuleTemplateList/ProjectTable/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/RuleTemplate/RuleTemplateList/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/RuleTemplate/RuleTemplateList/columns.tsx, packages/sqle/src/page/Whitelist/List/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/Whitelist/List/columns.tsx, packages/sqle/src/page/Whitelist/List/index.tsx, packages/sqle/src/page/Whitelist/__snapshots__/index.test.tsx.snap
fix:https://github.com/actiontech/dms/issues/129
=> [fix]: Optimize table column width

packages/base/src/page/CloudBeaver/List/__snapshots__/index.test.tsx.snap, packages/base/src/page/CloudBeaver/List/column.tsx, packages/base/src/page/CloudBeaver/List/index.test.tsx, packages/base/src/page/CloudBeaver/List/index.tsx, packages/base/src/page/CloudBeaver/__snapshots__/index.test.tsx.snap, packages/base/src/page/CloudBeaver/style.ts, packages/base/src/page/System/GlobalSetting/__snapshots__/index.test.tsx.snap, packages/base/src/page/System/GlobalSetting/index.test.tsx, packages/base/src/page/System/GlobalSetting/index.tsx
issue: https://github.com/actiontech/dms-ee/issues/256
工作台SQL操作记录导出、全局配置过期时间功能
=> [feature](CloudBeaver): export file and system config

packages/shared/lib/testUtil/mockAntDesignPlots.jsx, packages/sqle/src/page/ProjectOverview/component/SqlCount/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/ProjectOverview/component/SqlCount/index.test.tsx, packages/sqle/src/page/ProjectOverview/component/SqlCount/index.tsx
fix: https://github.com/actiontech/sqle-ee/issues/1574
=> [fix](ProjectOverview/SqlCount): Optimize percentage accuracy and chart display

packages/base/src/locale/zh-CN/dmsDataSource.ts, packages/base/src/page/DataSource/components/AddDataSource/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataSource/components/Form/FormItem/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataSource/components/Form/__snapshots__/index.ce.test.tsx.snap, packages/base/src/page/DataSource/components/Form/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataSource/components/List/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataSource/components/List/index.test.tsx, packages/base/src/page/DataSource/components/UpdateDataSource/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataSource/components/UpdateDataSource/index.test.tsx, packages/shared/lib/components/TestDatabaseConnectButton/__snapshots__/index.test.tsx.snap, packages/shared/lib/components/TestDatabaseConnectButton/index.test.tsx, packages/shared/lib/locale/en-US/common.ts, packages/shared/lib/locale/zh-CN/common.ts, packages/sqle/src/page/SqlExecWorkflow/Create/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Create/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Create/__tests__/index.test.tsx, packages/sqle/src/page/SqlExecWorkflow/Create/components/FormStep/SqlAuditInfoForm/SqlAuditInfoFormItem/DatabaseSelectionItems/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Create/components/FormStep/SqlAuditInfoForm/SqlAuditInfoFormItem/DatabaseSelectionItems/__tests__/__snapshots__/useTestDatabaseConnect.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Create/components/FormStep/SqlAuditInfoForm/SqlAuditInfoFormItem/DatabaseSelectionItems/__tests__/useTestDatabaseConnect.test.tsx
fix:https://github.com/actiontech/sqle/issues/2443
=> [fix](DatabaseSource): Unified data source names

packages/shared/lib/api/sqle/service/task/index.d.ts, packages/shared/lib/api/sqle/service/workflow/index.d.ts, packages/sqle/src/page/SqlExecWorkflow/List/column.tsx, packages/sqle/src/page/SqlExecWorkflow/List/components/ExportWorkflowButton/index.tsx, packages/sqle/src/page/SqlExecWorkflow/List/components/__tests__/ExportWorkflowButton.test.tsx, packages/sqle/src/page/SqlExecWorkflow/List/index.tsx
issue:https://github.com/actiontech/sqle/issues/2451
=> [fix](SqlExecWorkflow): Modifying instance parameters

packages/base/src/page/DataSource/components/BatchImportDataSource/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataSource/components/BatchImportDataSource/index.test.tsx, packages/base/src/page/DataSource/components/List/__snapshots__/index.ce.test.tsx.snap, packages/base/src/page/DataSource/components/List/index.ce.test.tsx, packages/base/src/page/DataSource/components/List/index.tsx, packages/base/src/page/Project/BatchImportDataSource/UploadForm/__snapshots__/index.test.tsx.snap, packages/base/src/page/Project/BatchImportDataSource/UploadForm/index.tsx, packages/base/src/page/Project/BatchImportDataSource/__snapshots__/index.test.tsx.snap, packages/base/src/page/Project/BatchImportDataSource/index.test.tsx, packages/base/src/router/router.base.tsx, packages/base/src/router/test/__snapshots__/router.ce.base.test.tsx.snap, packages/base/src/router/test/__snapshots__/router.ce.sqle.test.tsx.snap, packages/base/src/router/test/router.ce.base.test.tsx
issue:https://github.com/actiontech/dms-ee/issues/287
添加条件编译，修改表单控件名称
=> [fix]: Add conditional compilation and modify name

packages/base/src/locale/zh-CN/dmsMember.ts, packages/base/src/page/Member/Modal/Member/MemberForm.tsx, packages/base/src/page/Member/Modal/Member/__tests__/__snapshots__/AddMember.test.tsx.snap, packages/base/src/page/Member/Modal/Member/__tests__/__snapshots__/MemberForm.test.tsx.snap, packages/base/src/page/Member/Modal/Member/__tests__/__snapshots__/UpdateMember.test.tsx.snap, packages/sqle/src/locale/zh-CN/execWorkflow.ts, packages/sqle/src/locale/zh-CN/sqlAudit.ts, packages/sqle/src/page/SqlAudit/Create/SQLStatementForm/index.tsx, packages/sqle/src/page/SqlAudit/Create/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/SqlStatementFormItem/__tests__/SqlExecModeSelector.test.tsx, packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/SqlStatementFormItem/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/SqlStatementFormItem/components/SqlExecModeSelector.tsx, packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Create/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Create/__tests__/index.test.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/ModifySqlStatement/__tests__/__snapshots__/index.test.tsx.snap
fix: https://github.com/actiontech/sqle/issues/2459
=> [chore]:Add informational messages and  disabled rather than hide unsupported "sqls_file" mode

packages/base/src/page/DataExportManagement/Create/__tests__/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataExportManagement/Create/components/CreateTask/__tests__/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataExportManagement/Create/components/SubmitWorkflow/UpdateInfoDrawer/__snapshots__/index.test.tsx.snap, packages/shared/lib/components/ModeSwitcher/__snapshots__/index.test.tsx.snap, packages/shared/lib/components/ModeSwitcher/index.tsx, packages/shared/lib/components/ModeSwitcher/style.ts, packages/sqle/src/locale/zh-CN/execWorkflow.ts, packages/sqle/src/locale/zh-CN/sqlOptimization.ts, packages/sqle/src/page/SqlAudit/Create/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/SqlStatementFormItem/__tests__/SqlExecModeSelector.test.tsx, packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/SqlStatementFormItem/__tests__/__snapshots__/SqlExecModeSelector.ce.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/SqlStatementFormItem/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/SqlStatementFormItem/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/SqlStatementFormItem/components/SqlExecModeSelector.tsx, packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/SqlStatementFormItem/index.tsx, packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Create/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Create/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Create/__tests__/index.test.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/ModifySqlStatement/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlOptimization/Create/SQLInfoForm/DatabaseInfo.tsx, packages/sqle/src/page/SqlOptimization/Create/__snapshots__/index.test.tsx.snap
https://github.com/actiontech/sqle/issues/2459
1. 调整 ModeSwitcher 组件支持能作为 Tooltip children 使用
2. 创建工单时文件上线模式展示逻辑调整
优先级：高
=> [feature]: Modify ModeSwitcher to support Tooltip

packages/sqle/src/page/ProjectOverview/component/SqlCount/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/ProjectOverview/component/SqlCount/index.test.tsx, packages/sqle/src/page/ProjectOverview/component/SqlCount/index.tsx
fix:https://github.com/actiontech/sqle-ee/issues/1614
=> [fix](ProjectOverview): SQL statistical chart display issues

packages/base/src/page/Project/index.test.tsx, packages/base/src/page/Project/index.tsx
fix:https://github.com/actiontech/sqle-ee/issues/1623
=> [fix](Project): Button operation permission

packages/sqle/src/page/SqlExecWorkflow/Detail/__tests__/index.test.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/hooks/useAuditExecResultPanelSetup.ts, packages/sqle/src/page/SqlExecWorkflow/Detail/hooks/useInitDataWithRequest.ts, packages/sqle/src/page/SqlExecWorkflow/Detail/index.tsx
fix: https://github.com/actiontech/sqle/issues/2482
=> [feature](SqlExecWorkflow): Start polling request when workflow status is executingass

packages/shared/lib/components/ActiontechTable/hooks/test/__snapshots__/useTableAction.test.tsx.snap, packages/shared/lib/components/ActiontechTable/hooks/test/useTableAction.test.tsx, packages/shared/lib/components/ActiontechTable/hooks/useTableAction.tsx, packages/shared/lib/components/ActiontechTable/index.type.ts
=> [feature](ActiontechTable): MoreButtons Add Functional Configuration

packages/base/src/locale/en-US/dmsSyncDataSource.ts, packages/base/src/locale/zh-CN/dmsSyncDataSource.ts, packages/base/src/page/SyncDataSource/AddPage/__snapshots__/index.test.tsx.snap, packages/base/src/page/SyncDataSource/Form/__snapshots__/index.test.tsx.snap, packages/base/src/page/SyncDataSource/Form/index.tsx, packages/base/src/page/SyncDataSource/UpdatePage/__snapshots__/index.test.tsx.snap
https://github.com/actiontech/sqle-ee/issues/1622
=> [chore]:(SyncDataSource) Remove redundant tips text from form fields

packages/shared/lib/api/sqle/service/instance_audit_plan/index.d.ts, packages/shared/lib/api/sqle/service/instance_audit_plan/index.ts
https://github.com/actiontech/sqle-ee/issues/1576
=> [chore]:(refactor audit plan) rebuild api

packages/base/src/page/CloudBeaver/Drawer/CBSqlOperationAuditDetailDrawer.tsx, packages/base/src/page/CloudBeaver/Drawer/test/__snapshots__/CBSqlOperationAuditDetailDrawer.test.tsx.snap, packages/base/src/page/DataExportManagement/Common/AuditResultList/Table/AuditResultDrawer.tsx, packages/base/src/page/DataExportManagement/Common/AuditResultList/__snapshots__/index.test.tsx.snap, packages/sqle/src/components/ReportDrawer/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/components/ReportDrawer/__tests__/index.test.tsx, packages/sqle/src/components/ReportDrawer/index.tsx, packages/sqle/src/components/ReportDrawer/index.type.ts, packages/sqle/src/components/ReportDrawer/useAuditResultRuleInfo.ts, packages/sqle/src/page/PluginAudit/Drawer/AuditResultDrawer.tsx, packages/sqle/src/page/PluginAudit/Drawer/test/__snapshots__/AuditResultDrawer.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Common/AuditResultList/Table/AuditResultDrawer.tsx, packages/sqle/src/page/SqlExecWorkflow/Common/AuditResultList/Table/__tests__/__snapshots__/AuditResultDrawer.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Common/AuditResultList/Table/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Detail/components/AuditExecResultPanel/TaskResultList/Common/SqlStatementResultTable/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/Modal/StatusDrawer/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/Modal/StatusDrawer/index.tsx, packages/sqle/src/page/SqlManagementConf/Detail/ScanTypeSqlCollection/indx.tsx
=> [fix]: Loading status of sql audit result drawer

packages/sqle/src/page/SqlManagementConf/Common/ConfForm/DataSourceSelection/index.tsx, packages/sqle/src/page/SqlManagementConf/Common/ConfForm/ScanTypesSelection/index.data.ts, packages/sqle/src/page/SqlManagementConf/Common/ConfForm/ScanTypesSelection/index.tsx, packages/sqle/src/page/SqlManagementConf/Create/CreationResult/index.tsx, packages/sqle/src/page/SqlManagementConf/Create/index.tsx, packages/sqle/src/page/SqlManagementConf/Detail/index.tsx
https://github.com/actiontech/sqle-ee/issues/1576
=> [fix]:(SqlManagementConf) Filter unnecessary data and set the instance_audit_plan_id returned after successful creation

packages/sqle/src/page/SqlManagementConf/List/TableTaskTypeFilter/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagementConf/List/TableTaskTypeFilter/__tests__/index.test.tsx, packages/sqle/src/page/SqlManagementConf/List/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagementConf/List/__tests__/index.test.tsx, packages/sqle/src/testUtils/mockApi/instanceAuditPlan/data.ts, packages/sqle/src/testUtils/mockApi/instanceAuditPlan/index.ts
=> [test](SqlManagementConf): Add unit test case for List

packages/sqle/src/page/SqlExecWorkflow/Detail/__tests__/index.test.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/hooks/useAuditExecResultPanelSetup.ts, packages/sqle/src/page/SqlExecWorkflow/Detail/hooks/useInitDataWithRequest.ts, packages/sqle/src/page/SqlExecWorkflow/Detail/index.tsx
https://github.com/actiontech/sqle/issues/2482
解决工单详情轮询任务列表问题
=> [fix](SqlExecWorkflow): Polling request issue

packages/sqle/src/locale/zh-CN/execWorkflow.ts, packages/sqle/src/locale/zh-CN/sqlAudit.ts, packages/sqle/src/page/SqlAudit/Create/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/SqlStatementFormItem/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/SqlStatementFormItem/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlOptimization/Create/__snapshots__/index.test.tsx.snap
fix: https://github.com/actiontech/dms/issues/277
=> [chore]: Modify the description of the uploaded ZIP file

packages/shared/lib/api/sqle/service/SqlManage/index.d.ts, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/index.test.tsx, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/index.tsx
https://github.com/actiontech/sqle-ee/issues/1576
=> [feature]:(SqlManagement) add business filter parameters to export API

packages/shared/lib/components/ActiontechTable/components/ColumnsSetting.tsx, packages/shared/lib/components/ActiontechTable/components/test/ColumnsSetting.test.tsx, packages/shared/lib/components/ActiontechTable/hooks/test/useTableSettings.test.tsx, packages/shared/lib/components/ActiontechTable/hooks/useTableSettings.tsx, packages/shared/lib/components/ActiontechTable/index.type.ts
ActiontechTable column更新缓存数据问题
=> [fix](ActiontechTable): Column cache update logic

packages/sqle/src/page/SqlManagementConf/Common/ConfForm/ScanTypesDynamicParams/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagementConf/Common/ConfForm/ScanTypesDynamicParams/__tests__/index.test.tsx, packages/sqle/src/page/SqlManagementConf/Common/ConfForm/ScanTypesSelection/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagementConf/Common/ConfForm/ScanTypesSelection/__tests__/index.test.tsx, packages/sqle/src/page/SqlManagementConf/Common/ConfForm/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagementConf/Common/ConfForm/__tests__/index.test.tsx
=> [test](SqlManagementConf): Add unit test case for Common

packages/sqle/src/page/ProjectOverview/hooks/useChatsDataByAPI.ts
fix: https://github.com/actiontech/sqle/issues/2522
=> [fix](ProjectOverview): Refresh project parameters after switching projects

packages/sqle/src/page/ProjectOverview/hooks/useChatsDataByAPI.ts
link https://github.com/actiontech/dms-ui/pull/379
=> [fix](ProjectOverview): Remove projectId dependency

packages/sqle/src/page/SqlManagementConf/Detail/Overview/column.tsx, packages/sqle/src/page/SqlManagementConf/Detail/__tests__/__snapshots__/index.test.tsx.snap
=> [fix](SqlManagementConf): Modify the column style of the overview table

packages/sqle/src/page/ProjectOverview/component/SqlCount/index.tsx
=> [fix](ProjectOverview): Modify the accuracy of chart data

packages/sqle/src/locale/zh-CN/pushRule.ts, packages/sqle/src/page/PushRuleConfiguration/index.tsx
basefrom https://github.com/actiontech/dms-ui/pull/383
=> [feature]:(SqlManagementIssusPush) Add community preview page

packages/shared/lib/components/SystemConfigurationHub/components/ConfigModifyBtn/index.tsx, packages/shared/lib/components/SystemConfigurationHub/components/ConfigSwitch/index.tsx, packages/sqle/src/page/PushRuleConfiguration/components/SqlManagementIssuePush/index.tsx
https://github.com/actiontech/sqle/issues/2527
=> [chore]:(System、PushRule) Modify component props and avatar size

packages/shared/lib/api/sqle/service/audit_whitelist/index.d.ts, packages/shared/lib/api/sqle/service/blacklist/index.d.ts, packages/shared/lib/api/sqle/service/blacklist/index.enum.ts, packages/shared/lib/api/sqle/service/blacklist/index.ts, packages/shared/lib/api/sqle/service/common.d.ts, packages/shared/lib/api/sqle/service/common.enum.ts, packages/sqle/src/data/ModalName.ts, packages/sqle/src/locale/zh-CN/sqlManagement.ts, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/Modal/ChangePriority/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/Modal/ChangePriority/index.test.tsx, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/Modal/ChangePriority/index.tsx, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/Modal/index.test.tsx, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/Modal/index.tsx, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/column.tsx, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/index.test.tsx
https://github.com/actiontech/sqle-ee/issues/1765
=> [feature]: (SqlManagement) add support for changing priority functionality

packages/sqle/src/locale/zh-CN/sqlAudit.ts, packages/sqle/src/page/SqlAudit/List/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlAudit/List/index.test.tsx, packages/sqle/src/page/SqlAudit/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagementConf/Common/ConfForm/DataSourceSelection/index.tsx, packages/sqle/src/page/SqlManagementConf/Common/ConfForm/__tests__/__snapshots__/DataSourceSelection.test.tsx.snap, packages/sqle/src/page/SqlManagementConf/Common/ConfForm/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagementConf/Create/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagementConf/Update/__tests__/__snapshots__/index.test.tsx.snap
fix: https://github.com/actiontech/sqle/issues/2558
=> [chore]: optimize page

packages/base/src/App.tsx, packages/base/src/locale/index.ts
https://github.com/actiontech/sqle/issues/2543
=> [feature]: implement language preference switch based on browser settings

packages/sqle/src/page/SqlManagementException/Common/Form/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagementException/Common/Form/__tests__/index.test.tsx, packages/sqle/src/page/SqlManagementException/Common/Form/index.tsx, packages/sqle/src/page/SqlManagementException/List/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagementException/List/__tests__/index.test.tsx, packages/sqle/src/page/SqlManagementException/Modal/__tests__/Create.test.tsx, packages/sqle/src/page/SqlManagementException/Modal/__tests__/Update.test.tsx, packages/sqle/src/page/SqlManagementException/Modal/__tests__/__snapshots__/Create.test.tsx.snap, packages/sqle/src/page/SqlManagementException/Modal/__tests__/__snapshots__/Update.test.tsx.snap, packages/sqle/src/page/SqlManagementException/Modal/__tests__/index.test.tsx, packages/sqle/src/page/SqlManagementException/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/SqlManagementException/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagementException/__tests__/index.ce.test.tsx, packages/sqle/src/page/SqlManagementException/__tests__/index.test.tsx, packages/sqle/src/page/SqlManagementException/hooks/__tests__/useSqlManagementExceptionRedux.test.ts, packages/sqle/src/page/Whitelist/Drawer/test/AddWhitelist.test.tsx, packages/sqle/src/page/Whitelist/hooks/__tests__/useWhitelistRedux.test.ts, packages/sqle/src/testUtils/mockApi/blacklist/data.ts, packages/sqle/src/testUtils/mockApi/blacklist/index.ts, packages/sqle/src/testUtils/mockRedux.tsx
黑名单单元测试
link https://github.com/actiontech/dms-ui/pull/399
=> [test](SqlManagementException): Add unit test case

packages/shared/lib/api/sqle/service/common.d.ts, packages/shared/lib/components/ActiontechTable/hooks/useTableAction.tsx, packages/shared/lib/global/index.ts, packages/shared/lib/global/useUserOperationPermission/index.test.ts, packages/shared/lib/global/useUserOperationPermission/index.ts, packages/shared/lib/testUtil/mockHook/data.tsx, packages/shared/lib/testUtil/mockHook/mockUseUserOperationPermission.ts, packages/sqle/src/page/SqlManagementConf/Common/ConfForm/DataSourceSelection/index.tsx, packages/sqle/src/page/SqlManagementConf/Common/ConfForm/__tests__/DataSourceSelection.test.tsx, packages/sqle/src/page/SqlManagementConf/Create/__tests__/index.test.tsx, packages/sqle/src/page/SqlManagementConf/Detail/Overview/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagementConf/Detail/Overview/__tests__/index.test.tsx, packages/sqle/src/page/SqlManagementConf/Detail/Overview/column.tsx, packages/sqle/src/page/SqlManagementConf/Detail/Overview/index.tsx, packages/sqle/src/page/SqlManagementConf/Detail/Overview/index.type.ts, packages/sqle/src/page/SqlManagementConf/Detail/__tests__/index.test.tsx, packages/sqle/src/page/SqlManagementConf/Detail/index.tsx, packages/sqle/src/page/SqlManagementConf/List/__tests__/index.test.tsx, packages/sqle/src/page/SqlManagementConf/List/column.tsx, packages/sqle/src/page/SqlManagementConf/List/index.tsx
https://github.com/actiontech/sqle/issues/2523
目前只补充了最基本的单元测试，后续的 case 下周补
优先级：高。希望能尽快处理。。
=> [feature]:(SqlManagementConf) Add user and data source operation permissions

packages/base/src/App.tsx
=> [fix]: adjust logic for determining current language preference

packages/sqle/src/locale/zh-CN/sqlManagementException.ts, packages/sqle/src/locale/zh-CN/whitelist.ts, packages/sqle/src/page/SqlManagementException/Common/Form/index.tsx, packages/sqle/src/page/SqlManagementException/Modal/Update/index.tsx, packages/sqle/src/page/SqlManagementException/Modal/__tests__/__snapshots__/Update.test.tsx.snap, packages/sqle/src/page/SqlManagementException/index.type.ts, packages/sqle/src/page/Whitelist/Drawer/UpdateWhitelist.tsx, packages/sqle/src/page/Whitelist/Drawer/WhitelistForm.tsx, packages/sqle/src/page/Whitelist/Drawer/index.type.ts, packages/sqle/src/page/Whitelist/Drawer/test/__snapshots__/UpdateWhitelist.test.tsx.snap
https://github.com/actiontech/sqle-ee/issues/1785
=> [chore]: (WhiteList、SqlManagementException) add warning information to the form

packages/base/src/page/Nav/SideMenu/MenuList/menus/sqle.tsx
link https://github.com/actiontech/dms-ui/pull/409
=> [chore](Nav): Format of menu names[skip ci]

packages/shared/lib/components/SystemConfigurationHub/hooks/__tests__/__snapshots__/useConfigRender.test.tsx.snap, packages/shared/lib/components/SystemConfigurationHub/hooks/__tests__/__snapshots__/useConfigSwitchControls.test.tsx.snap, packages/shared/lib/components/SystemConfigurationHub/hooks/__tests__/useConfigRender.test.tsx, packages/shared/lib/components/SystemConfigurationHub/hooks/__tests__/useConfigSwitchControls.test.tsx
=> test:(SystemConfigurationHub/hooks) Add unit tests

packages/shared/lib/testUtil/common.tsx, packages/sqle/src/page/PipelineConfiguration/Common/ConfigurationForm/PipelineNodeField/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/PipelineConfiguration/Common/ConfigurationForm/PipelineNodeField/__tests__/index.test.tsx, packages/sqle/src/page/PipelineConfiguration/Common/ConfigurationForm/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/PipelineConfiguration/Common/ConfigurationForm/__tests__/index.test.tsx, packages/sqle/src/page/PipelineConfiguration/Common/ConfigurationForm/__tests__/usePipelineConfigurationFormState.test..tsx, packages/sqle/src/page/PipelineConfiguration/Modal/PipelineDetailModal/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/PipelineConfiguration/Modal/PipelineDetailModal/__tests__/index.test.tsx, packages/sqle/src/page/PipelineConfiguration/Update/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/PipelineConfiguration/Update/__tests__/index.test.tsx, packages/sqle/src/store/pipeline/index.test.ts, packages/sqle/src/testUtils/mockApi/pipeline/data.ts, packages/sqle/src/testUtils/mockApi/pipeline/index.ts, packages/sqle/src/testUtils/mockRedux.tsx
=> [test](PipelineConfiguration): Supplementary unit test case

packages/sqle/src/page/SqlExecWorkflow/Detail/__tests__/index.test.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/PageHeaderExtra/__test__/index.test.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/PageHeaderExtra/hooks/useWorkflowDetailAction.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/PageHeaderExtra/index.tsx
fix: https://github.com/actiontech/sqle/issues/2581
=> [chore]: Add confirmation step for closing work orders

packages/shared/lib/components/SystemConfigurationHub/components/ConfigSwitch/__snapshots__/index.test.tsx.snap, packages/shared/lib/components/SystemConfigurationHub/components/ConfigSwitch/index.test.tsx, packages/shared/lib/components/SystemConfigurationHub/components/ConfigSwitch/index.tsx, packages/sqle/src/page/PushRuleConfiguration/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/PushRuleConfiguration/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/PushRuleConfiguration/components/SqlManagementIssuePush/ConfigFields.tsx, packages/sqle/src/page/PushRuleConfiguration/components/SqlManagementIssuePush/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/PushRuleConfiguration/components/SqlManagementIssuePush/__tests__/index.test.tsx, packages/sqle/src/page/PushRuleConfiguration/components/SqlManagementIssuePush/index.tsx, packages/sqle/src/page/PushRuleConfiguration/components/SqlManagementIssuePush/useCurrentTime.ts, packages/sqle/src/page/PushRuleConfiguration/index.ce.test.tsx, packages/sqle/src/page/PushRuleConfiguration/index.test.tsx, packages/sqle/src/testUtils/mockApi/reportPushConfigService/data.ts, packages/sqle/src/testUtils/mockApi/reportPushConfigService/index.ts
=> [test]:(SqlManagementIssuePush) Add unit tests

packages/sqle/src/page/PushRuleConfiguration/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/PushRuleConfiguration/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/PushRuleConfiguration/components/WorkflowUpdateNotifier/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/PushRuleConfiguration/components/WorkflowUpdateNotifier/__tests__/index.test.tsx, packages/sqle/src/page/PushRuleConfiguration/components/WorkflowUpdateNotifier/index.tsx
=> [test]:(WorkflowUpdateNotifier) Add unit tests

packages/base/src/locale/en-US/dmsMenu.ts, packages/sqle/src/locale/en-US/index.ts, packages/sqle/src/locale/en-US/pipelineConfiguration.ts
https://github.com/actiontech/sqle/issues/2564
=> update Translation packages

packages/base/src/locale/zh-CN/dmsSystem.ts, packages/base/src/page/Project/Modal/BusinessDescription/index.tsx, packages/base/src/page/Project/Modal/__tests__/AddProject.test.tsx, packages/base/src/page/Project/Modal/__tests__/__snapshots__/AddProject.test.tsx.snap, packages/base/src/page/System/GlobalSetting/components/OrderExpiredHours.tsx
https://github.com/actiontech/sqle-ee/issues/1796
5、6
=> [chore]: resolve not  translated and the English version hiding images

packages/shared/lib/api/sqle/service/common.d.ts, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/column.tsx, packages/sqle/src/testUtils/mockApi/sqlManage/data.ts
https://github.com/actiontech/sqle/issues/2616
=> [feature]:(SqlManagement) Restore endpoint to accept array type for data consistency

packages/sqle/src/locale/zh-CN/index.ts, packages/sqle/src/locale/zh-CN/versionManagement.ts, packages/sqle/src/page/VersionManagement/List/column.tsx, packages/sqle/src/page/VersionManagement/List/index.tsx, packages/sqle/src/page/VersionManagement/index.data.ts, packages/sqle/src/page/VersionManagement/index.tsx
版本管理列表，目前删除、锁定等接口暂时未联调，可以先合并到临时分支，后续改动会重新提交pr
link https://github.com/actiontech/dms-ui/pull/426
=> [feature]: Version management list

packages/shared/lib/api/sqle/service/common.d.ts, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/column.tsx, packages/sqle/src/testUtils/mockApi/sqlManage/data.ts
Reverts actiontech/dms-ui#425
issue: https://github.com/actiontech/sqle/issues/2616
后端没处理该需求，还原前端代码
=> Revert "[feature]:(SqlManagement) Restore endpoint to accept array type for data consistency"

packages/base/src/locale/en-US/dmsMenu.ts, packages/sqle/src/locale/en-US/execWorkflow.ts, packages/sqle/src/locale/en-US/index.ts, packages/sqle/src/locale/en-US/versionManagement.ts
https://github.com/actiontech/sqle/issues/2657
=> translate version management

packages/base/src/page/System/License/index.test.tsx, packages/base/src/page/System/License/index.tsx
https://github.com/actiontech/sqle/issues/2626
特殊接口手动指定 Accept-Language
高优先级
=> [chore]: Manually set Accept-Language header for a specific API

packages/sqle/src/locale/en-US/execWorkflow.ts, packages/sqle/src/locale/zh-CN/execWorkflow.ts, packages/sqle/src/page/SqlExecWorkflow/Detail/__tests__/index.test.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/PageHeaderExtra/__test__/index.test.tsx
issue: https://github.com/actiontech/sqle/issues/2581
优化提示
=> [chore](SqlExecWorkflow): Optimize the prompt for closing workflow

packages/sqle/src/page/VersionManagement/Common/VersionForm/DeploymentConf/index.tsx, packages/sqle/src/page/VersionManagement/Create/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/VersionManagement/Create/__tests__/index.test.tsx, packages/sqle/src/page/VersionManagement/Create/index.tsx, packages/sqle/src/page/VersionManagement/List/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/VersionManagement/List/__tests__/index.test.tsx, packages/sqle/src/page/VersionManagement/Update/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/VersionManagement/Update/__tests__/index.test.tsx, packages/sqle/src/page/VersionManagement/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/VersionManagement/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/VersionManagement/__tests__/index.ce.test.tsx, packages/sqle/src/page/VersionManagement/__tests__/index.test.tsx, packages/sqle/src/testUtils/mockApi/sql_version/data.ts
=> [test](VersionManagement): Add unit test case

packages/base/src/page/DataSource/components/List/actions.tsx, packages/base/src/page/UserCenter/actions.tsx, packages/base/src/page/UserCenter/components/RoleList/List.tsx, packages/base/src/page/UserCenter/components/RoleList/action.ts, packages/base/src/page/UserCenter/components/RoleList/column.tsx, packages/base/src/page/UserCenter/components/UserList/List.tsx, packages/base/src/page/UserCenter/components/UserList/action.ts, packages/base/src/page/UserCenter/index.tsx, packages/shared/lib/global/usePermission/index.type.ts, packages/shared/lib/global/usePermission/permissionManifest.ts, packages/shared/lib/global/usePermission/permissions.ts, packages/shared/lib/global/usePermission/usePermission.ts
https://github.com/actiontech/sqle/issues/2672
重构用户中心操作权限相关代码
=> [feature]:(UserCenter) refactor action permission code [skip ci]

packages/base/src/locale/en-US/dmsMenu.ts, packages/base/src/locale/en-US/dmsSystem.ts
https://github.com/actiontech/sqle/issues/2657
=> Fix translation

packages/base/src/locale/en-US/dmsMenu.ts, packages/base/src/locale/en-US/dmsSystem.ts
cherry pick https://github.com/actiontech/dms-ui/pull/453
=> Cherry pick

packages/base/src/page/System/GlobalSetting/components/CBOperationLogsExpiredHours.tsx, packages/base/src/page/System/GlobalSetting/components/OperationRecordExpiredHours.tsx, packages/base/src/page/System/GlobalSetting/components/UrlAddressPrefixTips.tsx, packages/base/src/page/System/GlobalSetting/index.tsx, packages/base/src/page/System/License/action.tsx, packages/base/src/page/System/License/index.tsx, packages/base/src/page/System/LoginConnection/LDAPSetting/index.tsx, packages/base/src/page/System/LoginConnection/Oauth/index.tsx, packages/base/src/page/System/PersonalizeSetting/index.tsx, packages/base/src/page/System/ProcessConnection/DingTalkSetting/index.tsx, packages/base/src/page/System/ProcessConnection/LarkAuditSetting/index.ee.tsx, packages/base/src/page/System/ProcessConnection/WechatAuditSetting/index.tsx, packages/base/src/page/System/PushNotification/LarkSetting/index.tsx, packages/base/src/page/System/PushNotification/SMTPSetting/components/ConfigExtraButtons.tsx, packages/base/src/page/System/PushNotification/SMTPSetting/index.tsx, packages/base/src/page/System/PushNotification/WebhookSetting/index.tsx, packages/base/src/page/System/PushNotification/Wechat/index.tsx, packages/base/src/page/System/components/ConfigModifyBtn/index.tsx, packages/base/src/page/System/components/ConfigSwitch/index.tsx, packages/shared/lib/components/ActionButton/ActionButton.tsx, packages/shared/lib/components/ActionButton/index.type.ts, packages/shared/lib/components/ConfigItem/components/ImageUploader.tsx, packages/shared/lib/components/ConfigItem/index.type.ts, packages/shared/lib/global/usePermission/permissionManifest.ts, packages/shared/lib/global/usePermission/permissions.ts
https://github.com/actiontech/sqle/issues/2672
完成系统设置相关权限代码重构。
具体权限清单见：https://github.com/actiontech/sqle/issues/2672#issuecomment-2410117815
=> [feature]: (Base/System) refactor permission codes [skip ci]

packages/shared/lib/global/usePermission/permissionManifest.ts, packages/shared/lib/global/usePermission/permissions.ts, packages/shared/lib/global/usePermission/usePermission.ts, packages/sqle/src/page/SqlExecWorkflow/Detail/components/AuditExecResultPanel/OverviewList/action.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/AuditExecResultPanel/OverviewList/index.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/PageHeaderExtra/action.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/PageHeaderExtra/index.tsx, packages/sqle/src/page/SqlExecWorkflow/List/action.tsx, packages/sqle/src/page/SqlExecWorkflow/List/components/ExportWorkflowButton/index.tsx, packages/sqle/src/page/SqlExecWorkflow/List/index.tsx
https://github.com/actiontech/sqle/issues/2672
重构 SQL 工单相关权限代码
涉及的权限清单：https://github.com/actiontech/sqle/issues/2672#issuecomment-2416192239
=> [feature]:(SqlExecWorkflow) refactor permission codes [skip ci]

packages/sqle/src/locale/en-US/execWorkflow.ts, packages/sqle/src/locale/zh-CN/execWorkflow.ts, packages/sqle/src/page/SqlExecWorkflow/Common/SubmitWorkflowButton/__tests__/index.test.tsx, packages/sqle/src/page/SqlExecWorkflow/Common/SubmitWorkflowButton/index.tsx, packages/sqle/src/page/SqlExecWorkflow/Common/SubmitWorkflowButton/index.type.ts, packages/sqle/src/page/SqlExecWorkflow/Create/__tests__/index.test.tsx, packages/sqle/src/page/SqlExecWorkflow/Create/components/AuditResultStep/__tests__/index.test.tsx, packages/sqle/src/page/SqlExecWorkflow/Create/components/AuditResultStep/index.tsx, packages/sqle/src/page/SqlExecWorkflow/Create/components/AuditResultStep/index.type.ts, packages/sqle/src/page/SqlExecWorkflow/Create/hooks/__tests__/useAllowAuditLevel.test.ts, packages/sqle/src/page/SqlExecWorkflow/Create/hooks/__tests__/useAuditWorkflow.test.ts, packages/sqle/src/page/SqlExecWorkflow/Create/hooks/useAllowAuditLevel.ts, packages/sqle/src/page/SqlExecWorkflow/Create/hooks/useAuditWorkflow.tsx, packages/sqle/src/page/SqlExecWorkflow/Create/index.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/ModifySqlStatement/__tests__/index.test.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/ModifySqlStatement/index.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/ModifySqlStatement/index.type.ts, packages/sqle/src/page/SqlExecWorkflow/Detail/hooks/useModifySql.ts, packages/sqle/src/page/SqlExecWorkflow/Detail/index.tsx, packages/sqle/src/page/VersionManagement/Detail/components/ModifyWorkflowSql/index.tsx
https://github.com/actiontech/sqle/issues/2704
=> [feature]:(SqlExecWorkflow) Replace submit button disable with secondary confirmation  for workflow

packages/shared/lib/global/usePermission/index.type.ts, packages/shared/lib/global/usePermission/permissionManifest.ts, packages/shared/lib/global/usePermission/permissions.ts, packages/shared/lib/global/usePermission/usePermission.ts, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/column.tsx, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/hooks/useBatchIgnoreOrSolve.ts, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/index.data.ts, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/index.tsx
issue:https://github.com/actiontech/sqle/issues/2672
重构SQL管控相关权限代码,两个特殊权限场景暂未处理
涉及权限：https://github.com/actiontech/sqle/issues/2672#issuecomment-2437076202
=> [refactor](SqlManagement): Operation permission[skip ci]

packages/shared/lib/global/usePermission/permissionManifest.ts, packages/shared/lib/global/usePermission/permissions.ts, packages/sqle/src/page/SqlExecWorkflow/Common/AuditResultList/Table/actions.tsx, packages/sqle/src/page/SqlExecWorkflow/Common/AuditResultList/Table/column.tsx, packages/sqle/src/page/SqlExecWorkflow/Common/AuditResultList/Table/index.tsx, packages/sqle/src/page/Whitelist/List/actions.tsx, packages/sqle/src/page/Whitelist/List/index.tsx, packages/sqle/src/page/Whitelist/hooks/useWhitelistRedux.ts
issue: https://github.com/actiontech/sqle/issues/2672
- 重构审核SQL例外操作权限
- 重构工单-创建工单-sql审核结果-添加为审核sql例外权限
涉及权限：
https://github.com/actiontech/sqle/issues/2672#issuecomment-2440703607
https://github.com/actiontech/sqle/issues/2672#issuecomment-2416192239
=> [refactor](Whitelist): Operation permissions

packages/base/src/App.test.tsx, packages/base/src/page/CloudBeaver/List/__snapshots__/index.test.tsx.snap, packages/base/src/page/CloudBeaver/List/actions.tsx, packages/base/src/page/CloudBeaver/List/column.tsx, packages/base/src/page/CloudBeaver/List/index.test.tsx, packages/base/src/page/CloudBeaver/List/index.tsx, packages/base/src/page/DataSourceManagement/__tests__/index.ce.test.tsx, packages/base/src/page/DataSourceManagement/__tests__/index.test.tsx, packages/base/src/page/Nav/SideMenu/UserMenu/components/__tests__/GlobalSetting.test.tsx, packages/base/src/page/Nav/SideMenu/UserMenu/index.ce.test.tsx, packages/base/src/page/Nav/SideMenu/UserMenu/index.test.tsx, packages/base/src/page/Nav/SideMenu/__tests__/index.ce.test.tsx, packages/base/src/page/Nav/SideMenu/__tests__/index.test.tsx, packages/shared/lib/global/PermissionControl/index.test.tsx, packages/shared/lib/global/usePermission/permissionManifest.ts, packages/shared/lib/global/usePermission/permissions.ts, packages/shared/lib/testUtil/mockHook/data.tsx, packages/shared/lib/testUtil/mockHook/mockUsePermission.ts
issue: https://github.com/actiontech/sqle/issues/2672
权限清单：https://github.com/actiontech/sqle/issues/2672#issuecomment-2440422067
=> [refactor]:(CloudBeaver) refactor permission codes [skip ci]

packages/shared/lib/api/sqle/service/common.d.ts, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/column.tsx, packages/sqle/src/testUtils/mockApi/sqlManage/data.ts
issue: https://github.com/actiontech/sqle/issues/2616
Reverts actiontech/dms-ui#429
=> Revert "Revert "[feature]:(SqlManagement) Restore endpoint to accept array type for data consistency""

packages/sqle/src/page/SqlManagementConf/Detail/ScanTypeSqlCollection/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagementConf/Detail/ScanTypeSqlCollection/indx.tsx
link https://github.com/actiontech/dms-ui/pull/488
=> [fix](SqlManagementConf): Time type judgment

packages/base/src/page/CloudBeaver/List/index.test.tsx, packages/base/src/page/Project/List/action.ts, packages/base/src/page/Project/List/columns.tsx, packages/base/src/page/Project/List/index.test.tsx, packages/base/src/page/Project/List/index.tsx, packages/base/src/page/Project/__snapshots__/index.test.tsx.snap, packages/base/src/page/Project/action.tsx, packages/base/src/page/Project/index.test.tsx, packages/base/src/page/Project/index.tsx, packages/base/src/page/SyncDataSource/List/index.test.tsx, packages/base/src/page/System/PersonalizeSetting/index.test.tsx, packages/base/src/page/UserCenter/__tests__/index.test.tsx, packages/base/src/page/UserCenter/components/UserList/__tests__/UserList.test.tsx, packages/shared/lib/enum/index.ts, packages/shared/lib/global/PermissionControl/index.tsx, packages/shared/lib/global/useCurrentUser/index.test.ts, packages/shared/lib/global/useCurrentUser/index.ts, packages/shared/lib/global/usePermission/__tests__/__snapshots__/index.test.ts.snap, packages/shared/lib/global/usePermission/__tests__/index.test.ts, packages/shared/lib/global/usePermission/index.type.ts, packages/shared/lib/global/usePermission/permissionManifest.ts, packages/shared/lib/global/usePermission/permissions.ts, packages/shared/lib/global/usePermission/usePermission.ts, packages/shared/lib/testUtil/mockHook/data.tsx
https://github.com/actiontech/sqle/issues/2672
重构项目列表权限相关代码
权限清单：https://github.com/actiontech/sqle/issues/2672#issuecomment-2453895976
=> [feature]: (ProjectManagement) refactor permission codes

packages/sqle/src/components/ChartCom/TableTopList/index.tsx, packages/sqle/src/page/ProjectOverview/component/OrderRiskList/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/ProjectOverview/component/OrderRiskList/index.tsx
fix: https://github.com/actiontech/sqle/issues/2735
=> [fix](ProjectOverview): Style of work order list under project overview

packages/shared/lib/api/sqle/service/common.d.ts, packages/sqle/src/locale/zh-CN/dataSourceComparison.ts, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/component/ComparisonTreeNode/ComparisonDetailDrawer/index.tsx, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/component/EnvironmentSelector/index.tsx, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/component/ModifiedSqlDrawer/index.tsx, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/hooks/useComparisonResultTree.tsx, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/index.tsx, packages/sqle/src/page/SqlManagementConf/Detail/Overview/column.tsx
https://github.com/actiontech/sqle-ee/issues/1949
展示审核失败时的错误
=> [feature]: Display failure reasons on sql audit failure

packages/base/src/App.ce.test.tsx, packages/base/src/App.test.tsx, packages/base/src/App.tsx, packages/base/src/page/CloudBeaver/index.tsx
cb 社区版隐藏水印
cb 侧 pr：https://github.com/actiontech/cloudbeaver/pull/6
issue:https://github.com/actiontech/sqle-ee/issues/1962
=> [feature: Implement postMessage for two-way communication with cb

packages/sqle/src/page/DataSourceComparison/ComparisonEntry/component/ComparisonTreeNode/index.tsx, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/hooks/useComparisonResultTree.tsx, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/index.tsx
fix: https://github.com/actiontech/sqle-ee/issues/1963
=> [fix]: (DataSourceComparison) Resolve issue of using original data after filtering

packages/shared/lib/api/sqle/service/common.d.ts, packages/shared/lib/api/sqle/service/common.enum.ts, packages/sqle/src/locale/zh-CN/execWorkflow.ts, packages/sqle/src/page/SqlExecWorkflow/Common/AuditResultList/Table/index.data.ts, packages/sqle/src/page/SqlExecWorkflow/Detail/components/RecordInfo/components/AssociatedRollbackWorkflows.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/RecordInfo/components/AssociatedWorkflows.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/RecordInfo/index.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/RecordInfo/index.type.ts, packages/sqle/src/page/SqlExecWorkflow/Detail/components/SqlRollback/TableTransfer.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/SqlRollback/columns.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/SqlRollback/index.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/SqlRollback/style.ts
issue:https://github.com/actiontech/sqle-ee/issues/1956
- 添加关联回滚工单信息
link https://github.com/actiontech/dms-ui/pull/504
=> [feature](SqlExecWorkflow): Add associated workflow information[skip ci]

packages/shared/lib/api/sqle/service/common.d.ts, packages/shared/lib/api/sqle/service/workflow/index.ts
issue: https://github.com/actiontech/sqle-ee/issues/1956
=> [chore]: Update api

packages/sqle/src/page/RuleKnowledge/RuleUnderstand/__snapshots__/EditKnowledgeContent.test.tsx.snap, packages/sqle/src/page/RuleKnowledge/style.ts
https://github.com/actiontech/sqle-ee/issues/2089
markdown编辑器全屏模式下添加 background color
=> [chore]: (RuleKnowledge) fix MdEditor style issue in full screen mode

scripts/getGitVersion.mjs
https://github.com/actiontech/sqle/issues/2828
当当前分支存在 tag 时，使用 tag name 替换 branch name 作为版本号展示内容
=> [feature]:(scripts) version display content is adjusted from branch name to tag name [skip ci]

scripts/getGitVersion.mjs
https://github.com/actiontech/sqle/issues/2828
1. 调整 tag 格式
2. 使用 dirname + import.meta.filename 替换 import.meta.dirname, 后者需要 node v20+
basefrom https://github.com/actiontech/dms-ui/pull/532
=> [chore]: Adjust the __dirname acquisition method and tag format

packages/sqle/src/page/DataSourceComparison/ComparisonEntry/__tests__/ComparisonTreeNode.test.tsx, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/__tests__/ModifedSqlAuditResult.test.tsx, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/component/ComparisonTreeNode/ComparisonDetailDrawer/index.tsx, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/component/ModifiedSqlAuditResult/List.tsx, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/component/ModifiedSqlAuditResult/index.tsx
fix https://github.com/actiontech/sqle-ee/issues/2109
=> [fix]:(DataSourceComparison)  error message is not displayed when the  SQL audit fails

.apigeneratorrc, package.json
=> [feature]: Add API generated cli command

packages/sqle/src/components/SqlRewrittenDrawer/index.ee.tsx
https://github.com/actiontech/sqle-ee/issues/2037
=> [style]:(SqlRewrittenDrawer) fix title style inconsistency issue

packages/base/src/page/DataSource/components/Form/FormItem/index.tsx, packages/base/src/page/DataSource/components/Form/index.tsx, packages/sqle/src/components/BackendForm/FormPasswordWithPlaceholder.tsx, packages/sqle/src/components/BackendForm/__tests__/FormPasswordWithPlaceholder.test.tsx, packages/sqle/src/components/BackendForm/__tests__/__snapshots__/AutoCreatedFormItemByApi.test.tsx.snap, packages/sqle/src/components/BackendForm/useAsyncParams.ts, packages/sqle/src/page/SqlManagementConf/Common/ConfForm/__tests__/__snapshots__/ScanTypesDynamicParams.test.tsx.snap, packages/sqle/src/page/SqlManagementConf/Create/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagementConf/Update/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagementConf/Update/__tests__/index.test.tsx, packages/sqle/src/page/SqlManagementConf/Update/index.tsx
https://github.com/actiontech/sqle-ee/issues/2099
=> [fix](SqlManagementConf/Update): exclude updating password field when it's empty

packages/base/src/router/test/__snapshots__/router.sqle.test.tsx.snap, packages/base/src/router/test/router.base.test.tsx, packages/base/src/router/test/router.ce.base.test.tsx, packages/base/src/router/test/router.ce.sqle.test.tsx, packages/base/src/router/test/router.sqle.test.tsx
=> [test](base/router): Fix testing errors

scripts/cli/create-dms-page/src/module/icon-manager/index.ts, scripts/cli/create-dms-page/src/utils/path-utils.ts, scripts/cli/create-dms-page/src/utils/platform.ts
=> [fix]: Error in create-dms-page cli

packages/base/src/page/DataExportManagement/Common/AuditResultList/Table/index.tsx, packages/sqle/src/components/SqlRewrittenDrawer/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/components/SqlRewrittenDrawer/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/components/SqlRewrittenDrawer/__tests__/components/DependDatabaseStructure.test.tsx, packages/sqle/src/components/SqlRewrittenDrawer/__tests__/index.ce.test.tsx, packages/sqle/src/components/SqlRewrittenDrawer/__tests__/index.ee.test.tsx, packages/sqle/src/components/SqlRewrittenDrawer/components/DependDatabaseStructure/index.tsx, packages/sqle/src/components/SqlRewrittenDrawer/index.ce.tsx, packages/sqle/src/components/SqlRewrittenDrawer/index.ee.tsx, packages/sqle/src/components/SqlRewrittenDrawer/index.tsx, packages/sqle/src/components/SqlRewrittenDrawer/index.type.ts, packages/sqle/src/locale/zh-CN/sqlRewrite.ts, packages/sqle/src/page/SqlExecWorkflow/Common/AuditResultList/Table/index.tsx, packages/sqle/src/page/SqlManagementConf/Update/index.tsx
https://github.com/actiontech/sqle-ee/issues/2037
SQL 重写功能添加前端数据缓存功能，并提供 更新重写结果 按钮。
=> [feature]:(SqlRewrittenDrawer): add SQL rewrite data caching

packages/base/src/page/Nav/SideMenu/MenuList/index.tsx
fix issue: https://github.com/actiontech/dms-ee/issues/438
=> [fix]: (SideMenu) hide menu groups with no submenus

.github/workflows/main.yml, packages/shared/lib/api/sqle/service/common.enum.ts, packages/sqle/src/hooks/useBackendTable/__snapshots__/useBackendTable.test.tsx.snap, packages/sqle/src/hooks/useBackendTable/useBackendTable.test.tsx, packages/sqle/src/hooks/useBackendTable/useBackendTable.tsx
issue: https://github.com/actiontech/sqle-ee/issues/2141
main 分支变更预计会在下周处理
=> [feature]:(uesBackendTable) add "day_range" type to FilterMetaFilterInputTypeEnum for dynamic filter generation

packages/base/src/page/Nav/SideMenu/MenuList/index.tsx, packages/base/src/page/Nav/SideMenu/MenuList/menus/__tests__/__snapshots__/common.test.tsx.snap, packages/base/src/page/Nav/SideMenu/MenuList/menus/__tests__/common.test.tsx, packages/base/src/page/Nav/SideMenu/MenuList/menus/base.tsx, packages/base/src/page/Nav/SideMenu/MenuList/menus/common.ts, packages/base/src/page/Nav/SideMenu/MenuList/menus/index.type.ts, packages/base/src/page/Nav/SideMenu/MenuList/menus/menu.data.dms.tsx, packages/base/src/page/Nav/SideMenu/MenuList/menus/menu.data.tsx, packages/base/src/page/Nav/SideMenu/MenuList/menus/sqle.tsx
fix issue: https://github.com/actiontech/sqle/issues/2863
=> [fix]: refactor menu code to resolve i18n package errors

packages/base/src/App.test.tsx, packages/base/src/App.tsx
fix:https://github.com/actiontech/sqle/issues/2865
=> [fix](base/App): Modified source data while verifying routing permissions

packages/base/src/page/DataExportManagement/Common/AuditResultList/Table/actions.tsx, packages/base/src/page/DataExportManagement/Common/AuditResultList/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataExportManagement/Common/AuditResultList/index.test.tsx, packages/base/src/page/DataExportManagement/Create/__tests__/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataExportManagement/Create/components/SubmitWorkflow/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/components/SqlRewrittenDrawer/__tests__/components/OverallRewrittenSuggestion.test.tsx, packages/sqle/src/components/SqlRewrittenDrawer/__tests__/components/RewrittenSuggestionDetails.test.tsx, packages/sqle/src/components/SqlRewrittenDrawer/__tests__/components/__snapshots__/OverallRewrittenSuggestion.test.tsx.snap, packages/sqle/src/components/SqlRewrittenDrawer/__tests__/components/__snapshots__/RewrittenSuggestionDetails.test.tsx.snap, packages/sqle/src/components/SqlRewrittenDrawer/components/Common/actions.tsx, packages/sqle/src/components/SqlRewrittenDrawer/components/RewrittenSuggestionDetails/RewrittenSuggestionItem.tsx, packages/sqle/src/components/SqlRewrittenDrawer/index.ee.tsx, packages/sqle/src/components/SqlRewrittenDrawer/index.type.ts, packages/sqle/src/locale/zh-CN/sqlRewrite.ts, packages/sqle/src/page/SqlExecWorkflow/Common/AuditResultList/Table/AuditResultDrawer.tsx, packages/sqle/src/page/SqlExecWorkflow/Common/AuditResultList/Table/__tests__/AuditResultDrawer.test.tsx, packages/sqle/src/page/SqlExecWorkflow/Common/AuditResultList/Table/__tests__/__snapshots__/AuditResultDrawer.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Common/AuditResultList/Table/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Common/AuditResultList/Table/__tests__/index.test.tsx, packages/sqle/src/page/SqlExecWorkflow/Common/AuditResultList/Table/index.tsx, packages/sqle/src/page/SqlExecWorkflow/Common/AuditResultList/Table/index.type.ts, packages/sqle/src/page/SqlExecWorkflow/Detail/components/AuditExecResultPanel/TaskResultList/Common/SqlStatementResultTable/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/testUtils/mockApi/task/data.ts
fix issue: https://github.com/actiontech/sqle-ee/issues/2150
=> [chore]: optimize SQLRewriteDrawer

packages/sqle/src/page/SqlAnalyze/ManagementConf/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlAnalyze/ManagementConf/index.test.tsx, packages/sqle/src/page/SqlAnalyze/ManagementConf/index.tsx, packages/sqle/src/page/SqlAnalyze/SqlManage/index.tsx, packages/sqle/src/page/SqlAnalyze/hooks/useSqlExecPlanCost.ts
issue:https://github.com/actiontech/sqle-ee/issues/2134
SQL管控配置-SQL分析添加趋势图
=> [feature](SqlAnalyze/ManagementConf): Add SQL execution plan cost chart

packages/base/src/locale/zh-CN/dmsDataExport.ts, packages/base/src/page/DataExportManagement/Common/AuditResultList/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataExportManagement/Create/components/SubmitWorkflow/SubmitWorkflowButton/__tests__/index.test.tsx, packages/base/src/page/DataExportManagement/Create/components/SubmitWorkflow/SubmitWorkflowButton/index.tsx, packages/sqle/src/components/ReportDrawer/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/components/ReportDrawer/__tests__/index.test.tsx, packages/sqle/src/components/ReportDrawer/index.tsx, packages/sqle/src/components/ReportDrawer/index.type.ts, packages/sqle/src/components/ReportDrawer/style.ts, packages/sqle/src/components/ReportDrawer/useAuditResultRuleInfo.ts, packages/sqle/src/locale/zh-CN/auditPlan.ts, packages/sqle/src/page/SqlExecWorkflow/Common/AuditResultList/Table/__tests__/__snapshots__/AuditResultDrawer.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Common/SubmitWorkflowButton/__tests__/index.test.tsx, packages/sqle/src/page/SqlExecWorkflow/Common/SubmitWorkflowButton/index.tsx, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/Modal/StatusDrawer/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagementConf/Detail/ScanTypeSqlCollection/__tests__/__snapshots__/index.test.tsx.snap
https://github.com/actiontech/sqle/issues/2868
处理产品验收问题
=> [chore]: resolved all review comments

packages/base/src/App.tsx
=> [refactor]: Refactoring route initialization permission judgment method

scripts/cli/create-dms-page/src/module/menu-manager/index.ts, scripts/cli/create-dms-page/src/utils/babel-utils.ts
根据菜单项的结构变化调整生成函数
basefrom https://github.com/actiontech/dms-ui/pull/555
=> [chore]:(cli/create-dms-page) adjust generation function based on menu item structural changes

packages/base/src/page/DataSource/components/List/__snapshots__/index.test.tsx.snap, packages/base/src/page/DataSource/components/List/index.test.tsx, packages/base/src/page/DataSource/components/List/index.tsx
https://github.com/actiontech/sqle/issues/2851
=> [feature](base): refresh data source list after testing connection

packages/base/src/page/Nav/SideMenu/QuickActions/index.tsx, packages/sqle/src/locale/zh-CN/knowledgeBase.ts, packages/sqle/src/page/Knowledge/Common/KnowledgeSearchBar/TagSelectorBar/index.tsx, packages/sqle/src/page/Knowledge/Common/KnowledgeSearchBar/hooks/useKnowledgeSearchBar.ts, packages/sqle/src/page/Knowledge/Common/KnowledgeSearchBar/index.tsx, packages/sqle/src/page/Knowledge/Common/KnowledgeSearchBar/index.type.ts, packages/sqle/src/page/Knowledge/Common/KnowledgeSearchBar/style.ts, packages/sqle/src/page/Knowledge/RefineResults/index.tsx, packages/sqle/src/page/Knowledge/index.tsx
basefrom https://github.com/actiontech/dms-ui/pull/580
=> [feature]: Adjust KnowledgeSearchBar component[skip ci]

packages/base/public/static/image/knowledge.svg, packages/base/src/page/Nav/SideMenu/QuickActions/index.tsx, packages/sqle/package.json, packages/sqle/src/locale/zh-CN/knowledgeBase.ts, packages/sqle/src/page/Knowledge/Common/KnowledgeSearchBar/index.tsx, packages/sqle/src/page/Knowledge/Graph/common/LoadGraph.tsx, packages/sqle/src/page/Knowledge/Graph/common/data.ts, packages/sqle/src/page/Knowledge/Graph/hooks/useGraph.ts, packages/sqle/src/page/Knowledge/Graph/index.tsx, packages/sqle/src/page/Knowledge/Graph/index.type.ts, packages/sqle/src/page/Knowledge/Graph/style.ts, packages/sqle/src/page/Knowledge/RefineResults/index.tsx, packages/sqle/src/page/Knowledge/index.ee.tsx, packages/sqle/src/page/Knowledge/index.tsx, packages/sqle/src/router/config.tsx, packages/sqle/src/theme/dark/knowledge.ts, packages/sqle/src/theme/light/knowledge.ts, packages/sqle/src/theme/type.ts, pnpm-lock.yaml
basefrom https://github.com/actiontech/dms-ui/pull/580
=> [feature](sqle/knowledge): optimize permission control and graph rendering

packages/sqle/src/page/Knowledge/Graph/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/Knowledge/Graph/components/LoadGraph.tsx, packages/sqle/src/page/Knowledge/Graph/index.tsx
fix issue comment:  https://github.com/actiontech/sqle-ee/issues/2192#issuecomment-2683963150
=> [chore](KnowledgeGraph): Add reset clickedNode state on focus and change events

.github/workflows/main.yml, packages/sqle/src/hooks/useRuleVersionTips/index.test.tsx, packages/sqle/src/hooks/useRuleVersionTips/index.tsx, packages/sqle/src/page/GlobalRuleTemplate/CreateRuleTemplate/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/GlobalRuleTemplate/CreateRuleTemplate/index.test.tsx, packages/sqle/src/page/GlobalRuleTemplate/ImportRuleTemplate/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/GlobalRuleTemplate/UpdateRuleTemplate/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/Rule/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/Rule/index.test.tsx, packages/sqle/src/page/RuleTemplate/CreateRuleTemplate/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/RuleTemplate/CreateRuleTemplate/index.test.tsx, packages/sqle/src/page/RuleTemplate/ImportRuleTemplate/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/RuleTemplate/UpdateRuleTemplate/__snapshots__/index.test.tsx.snap
https://github.com/actiontech/sqle/issues/2935
=> [chore](useRuleVersionTIps): Add 'v' prefix to options label for version identification

packages/sqle/src/page/RuleTemplate/RuleTemplateList/index.test.tsx, packages/sqle/src/page/RuleTemplate/RuleTemplateList/index.tsx
Reverts actiontech/dms-ui#597
回退原因：https://github.com/actiontech/sqle/issues/2932#issuecomment-2690008740
=> Revert "[feature](RuleTemplate): add permission check for global rule template"

packages/base/src/router/test/__snapshots__/router.ce.sqle.test.tsx.snap, packages/base/src/router/test/__snapshots__/router.sqle.test.tsx.snap, packages/sqle/src/router/config.tsx
fix issue  https://github.com/actiontech/sqle/issues/2939
=> [fix]:(RuleTemplate) Remove permission restriction from GlobalRuleTemplateDetail route

packages/base/src/page/CloudBeaver/__snapshots__/index.ce.test.tsx.snap, packages/base/src/page/DataExportManagement/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/base/src/page/DataSourceManagement/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/base/src/page/GlobalDataSource/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/base/src/page/Nav/SideMenu/UserMenu/Modal/VersionModal/test/__snapshots__/index.ce.test.tsx.snap, packages/base/src/page/SyncDataSource/__snapshots__/index.ce.test.tsx.snap, packages/base/src/page/System/LoginConnection/Oauth/__snapshots__/index.ce.test.tsx.snap, packages/base/src/page/System/LoginConnection/__snapshots__/index.ce.test.tsx.snap, packages/base/src/page/System/ProcessConnection/__snapshots__/index.ce.test.tsx.snap, packages/base/src/page/System/__snapshots__/index.ce.test.tsx.snap, packages/shared/lib/components/EnterpriseFeatureDisplay/__snapshots__/EnterpriseFeatureDisplay.ce.test.tsx.snap, packages/shared/lib/components/EnterpriseFeatureDisplay/components/__tests__/__snapshots__/VersionComparison.test.tsx.snap, packages/shared/lib/locale/zh-CN/common.ts, packages/sqle/src/components/SqlRewrittenDrawer/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/DataSourceComparison/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/GlobalDashboard/List/PendingSql/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/Knowledge/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/OperationRecord/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/PluginAudit/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/PushRuleConfiguration/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/ReportStatistics/__snapshots__/ce.test.tsx.snap, packages/sqle/src/page/RuleManager/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/SqlManagement/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/SqlManagementException/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/SqlOptimization/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/VersionManagement/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/Whitelist/__snapshots__/ce.test.tsx.snap
调整产品不同版本之间的功能对比说明
https://github.com/actiontech/sqle-ee/issues/2261
=> [docs]: Update product version comparison descriptions

packages/shared/lib/api/sqle/service/common.d.ts, packages/sqle/src/page/SqlAnalyze/ManagementConf/index.tsx, packages/sqle/src/page/SqlAnalyze/SqlManage/index.tsx, packages/sqle/src/page/SqlAnalyze/hooks/__tests__/useSqlExecPlanCost.test.tsx, packages/sqle/src/page/SqlAnalyze/hooks/useSqlExecPlanCost.ts
issue:https://github.com/actiontech/sqle-ee/issues/2267
=> [fix](SqlAnalyze): Modify error message display

packages/base/src/locale/zh-CN/dmsSystem.ts, packages/base/src/page/System/LoginConnection/Oauth/__snapshots__/index.test.tsx.snap, packages/base/src/page/System/LoginConnection/Oauth/components/ConfigField.tsx, packages/base/src/page/System/LoginConnection/Oauth/components/__snapshots__/ConfigField.test.tsx.snap, packages/base/src/page/System/LoginConnection/Oauth/index.test.tsx, packages/base/src/page/System/LoginConnection/Oauth/index.tsx, packages/base/src/page/System/LoginConnection/Oauth/index.type.ts, packages/base/src/page/System/LoginConnection/__snapshots__/index.test.tsx.snap, packages/base/src/testUtils/mockApi/system/data.ts, packages/shared/lib/api/base/service/Session/index.d.ts, packages/shared/lib/api/base/service/Session/index.ts, packages/shared/lib/api/base/service/common.d.ts, packages/shared/lib/api/base/utils/Api.ts, packages/shared/lib/api/common/ApiBase/index.test.ts, packages/shared/lib/api/common/ApiBase/index.ts, packages/shared/lib/api/common/authInvalid/index.test.tsx, packages/shared/lib/api/common/authInvalid/index.ts, packages/shared/lib/api/sqle/utils/Api.ts
https://github.com/actiontech/sqle-ee/issues/2265
https://github.com/actiontech/sqle-ee/issues/2278
https://github.com/actiontech/sqle-ee/issues/2279
=> [feature](base/Oauth2): update OAuth2 configuration and refresh token mechanism

packages/base/src/page/Nav/SideMenu/UserMenu/components/ContextMenu/index.tsx, packages/base/src/page/Nav/SideMenu/UserMenu/components/__tests__/__snapshots__/GlobalSetting.test.tsx.snap, packages/base/src/page/Nav/SideMenu/UserMenu/components/__tests__/__snapshots__/UserNavigate.ce.test.tsx.snap, packages/base/src/page/Nav/SideMenu/UserMenu/components/__tests__/__snapshots__/UserNavigate.test.tsx.snap, packages/shared/lib/styleWrapper/nav.ts
fix:https://github.com/actiontech/dms/issues/359
=> [fix](Nav): Display optimization for usernames that are too long

scripts/getGitVersion.mjs
fix issue: https://github.com/actiontech/sqle/issues/3003
=> [fix]: select latest created tag when multiple tags exist [skip ci]

packages/base/src/page/DataSource/components/Form/index.test.tsx, packages/base/src/page/DataSource/components/Form/index.tsx
fix: https://github.com/actiontech/sqle/issues/3007
=> [fix](DataSource): Unable to select after resetting the project form field

packages/sqle/src/page/DataSourceComparison/ComparisonEntry/__tests__/__snapshots__/ComparisonTreeNode.test.tsx.snap, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/component/ComparisonTreeNode/index.tsx
为 Tree 添加 height 属性，开启虚拟滚动，解决数据量多大卡顿的问题
issue: https://github.com/actiontech/sqle-ee/issues/2316
优先级：高
=> [feature](sqle/DataSOurceComparison) add height property to enable virtual scrolling

packages/base/src/locale/zh-CN/dmsSystem.ts, packages/base/src/page/System/LoginConnection/LDAPSetting/__snapshots__/index.test.tsx.snap, packages/base/src/page/System/LoginConnection/LDAPSetting/components/ConfigField.test.tsx, packages/base/src/page/System/LoginConnection/LDAPSetting/components/ConfigField.tsx, packages/base/src/page/System/LoginConnection/LDAPSetting/components/__snapshots__/ConfigField.test.tsx.snap, packages/base/src/page/System/LoginConnection/LDAPSetting/index.test.tsx, packages/base/src/page/System/LoginConnection/LDAPSetting/index.tsx, packages/base/src/page/System/LoginConnection/LDAPSetting/index.type.ts, packages/base/src/page/System/LoginConnection/__snapshots__/index.ce.test.tsx.snap, packages/base/src/page/System/LoginConnection/__snapshots__/index.test.tsx.snap
issue:https://github.com/actiontech/dms/issues/385
=> [feature](base): add required fields validation and password update control

packages/base/src/locale/zh-CN/resourceOverview.ts, packages/sqle/src/locale/zh-CN/reportStatistics.ts, packages/sqle/src/page/ReportStatistics/EEIndex/component/charts/DatabaseSourceOrder/__snapshots__/index.test.tsx.snap
link https://github.com/actiontech/dms-ui/pull/635
修改文案提示
=> [chore](ReportStatistics&ResourceOverview): Modify empty tips of datasource chart

packages/sqle/src/locale/zh-CN/managementConf.ts, packages/sqle/src/page/SqlManagementConf/Common/ConfForm/ScanTypesDynamicParams/HighPriorityConditions/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagementConf/Common/ConfForm/ScanTypesDynamicParams/HighPriorityConditions/__tests__/index.test.tsx, packages/sqle/src/page/SqlManagementConf/Common/ConfForm/ScanTypesDynamicParams/HighPriorityConditions/index.tsx, packages/sqle/src/page/SqlManagementConf/Common/ConfForm/__tests__/__snapshots__/ScanTypesDynamicParams.test.tsx.snap, packages/sqle/src/page/SqlManagementConf/Create/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagementConf/Update/__tests__/__snapshots__/index.test.tsx.snap
issue: https://github.com/actiontech/sqle-ee/issues/2352
=> [chore](SqlManagementConf/Create): add tooltip for high priority SQL marking field

Makefile
basefrom https://github.com/actiontech/dms-ui/pull/620
更新 Makefile 中的 pnpm docker 镜像
优先级：高
=> [ci]: update docker image

packages/sqle/src/page/WorkflowTemplate/UpdateWorkflowTemplate/components/ReviewNodeInfo/index.tsx
fix issue:https://github.com/actiontech/sqle-ee/issues/2355
=> [feature](sqle/WorkflowTemplate): add filterOption for user selection

packages/base/src/hooks/useRecentlySelectedZone/__tests__/index.test.tsx, packages/base/src/hooks/useRecentlySelectedZone/index.ts, packages/base/src/page/AvailabilityZone/List/action.tsx, packages/base/src/page/Nav/SideMenu/UserMenu/components/UserNavigate.tsx, packages/base/src/page/Nav/SideMenu/UserMenu/components/__tests__/UserNavigate.test.tsx, packages/base/src/testUtils/mockHooks/data.tsx
issue:https://github.com/actiontech/dms-ee/issues/541
退出登录时重置可用区缓存数据
=> [feature](Nav): Clear zone storage when logging out

packages/base/src/hooks/useThemeStyleData/__snapshots__/index.test.tsx.snap, packages/sqle/src/locale/zh-CN/dataSourceComparison.ts, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/__tests__/ComparisonOverview.test.tsx, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/__tests__/ComparisonTreeNode.test.tsx, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/__tests__/TreeNode.test.tsx, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/__tests__/__snapshots__/ComparisonOverview.test.tsx.snap, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/__tests__/__snapshots__/ComparisonTreeNode.test.tsx.snap, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/__tests__/__snapshots__/useComparisonResultTree.test.tsx.snap, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/__tests__/index.test.tsx, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/component/ComparisonOverview/index.data.ts, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/component/ComparisonOverview/index.tsx, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/component/ComparisonOverview/style.ts, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/component/ComparisonTreeNode/index.tsx, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/component/ComparisonTreeNode/style.ts, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/hooks/useComparisonResultTree.tsx, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/index.tsx, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/style.ts, packages/sqle/src/page/DataSourceComparison/ComparisonEntry/utils/TreeNode.tsx, packages/sqle/src/page/DataSourceComparison/__tests__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/DataSourceComparison/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/DataSourceComparison/index.tsx, packages/sqle/src/page/DataSourceComparison/style.ts, packages/sqle/src/theme/dark/dataSourceComparison.ts, packages/sqle/src/theme/light/dataSourceComparison.ts, packages/sqle/src/theme/type.ts
fix issue: https://github.com/actiontech/sqle-ee/issues/2357
=> [refactor](sqle/DataSourceComparison): optimize structure and style adjustments

packages/shared/lib/api/common/authInvalid/index.test.tsx, packages/shared/lib/api/common/authInvalid/index.ts
fix issue: https://github.com/actiontech/sqle-ee/issues/2361
=> [fix](auth): handle token refresh failures properly

packages/base/src/locale/zh-CN/dmsSystem.ts, packages/base/src/page/System/DatabaseAccountPasswordPolicy/index.tsx, packages/base/src/page/System/index.enum.ts, packages/base/src/page/System/index.tsx
link https://github.com/actiontech/dms-ui-ee/pull/466
=> [feature](System): Add database account password policy wrapper

packages/base/src/App.test.tsx, packages/base/src/App.tsx
issue:https://github.com/actiontech/sqle/issues/3063
=> [fix](base/App): Remove token dependency for basic info reqeust

packages/base/src/page/CloudBeaver/__snapshots__/index.ce.test.tsx.snap, packages/base/src/page/CloudBeaver/__snapshots__/index.test.tsx.snap, packages/base/src/page/CloudBeaver/index.ce.test.tsx, packages/base/src/page/CloudBeaver/index.test.tsx, packages/base/src/page/CloudBeaver/index.tsx
basefrom https://github.com/actiontech/dms-ui/pull/683
=> feat: change CloudBeaver auto-redirect behavior from new tab to current window

packages/base/src/App.tsx, packages/base/src/page/Nav/SideMenu/MenuList/index.tsx, packages/base/src/page/Nav/SideMenu/MenuList/menus/__tests__/__snapshots__/common.test.tsx.snap, packages/base/src/page/Nav/SideMenu/MenuList/menus/sqle.tsx, packages/shared/lib/features/usePermission/__tests__/__snapshots__/index.test.ts.snap, packages/shared/lib/features/usePermission/__tests__/index.test.ts, packages/shared/lib/features/usePermission/index.type.ts, packages/shared/lib/features/usePermission/permissionManifest.ts, packages/shared/lib/features/usePermission/permissions.ts, packages/shared/lib/features/usePermission/usePermission.ts, packages/sqle/src/page/GlobalDashboard/List/PendingSql/PendingSqlList.tsx, packages/sqle/src/page/GlobalDashboard/List/PendingSql/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/GlobalDashboard/List/PendingSql/__tests__/index.test.tsx, packages/sqle/src/page/GlobalDashboard/List/PendingSql/actions.tsx, packages/sqle/src/page/GlobalDashboard/List/PendingSql/column.tsx, packages/sqle/src/page/GlobalDashboard/__tests__/index.test.tsx, packages/sqle/src/router/config.tsx
https://github.com/actiontech/sqle-ee/issues/2448
=> [feature]: add permission control for navigation menus and routing

packages/base/src/page/BindUser/__snapshots__/index.test.tsx.snap, packages/base/src/page/BindUser/index.test.tsx, packages/base/src/page/BindUser/index.tsx, packages/base/src/page/Login/__snapshots__/index.test.tsx.snap, packages/base/src/page/Login/components/LoginForm.tsx, packages/shared/lib/data/routePaths.ts
issue: https://github.com/actiontech/sqle-ee/issues/2448
=> [feature]: support redirecting to the target page after successful oauth2 login on the login page

packages/sqle/src/page/SqlManagement/component/SQLEEIndex/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/actions.tsx, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/index.test.tsx, packages/sqle/src/page/SqlManagement/component/SQLEEIndex/index.tsx
fix:https://github.com/actiontech/sqle-ee/issues/2439
=> [fix](SqlManagement): SQL operations can be performed when the user is assignees

packages/sqle/src/page/SqlInsights/components/RelatedSqlList/data.ts, packages/sqle/src/page/SqlInsights/components/SlowSqlTrend/index.tsx, packages/sqle/src/page/SqlInsights/components/__test__/ActiveSessionTrend.test.tsx, packages/sqle/src/page/SqlInsights/components/__test__/DataSourcePerformanceTrend.test.tsx, packages/sqle/src/page/SqlInsights/components/__test__/SlowSqlTrend.test.tsx, packages/sqle/src/page/SqlInsights/components/__test__/TopSqlTrend.test.tsx
link https://github.com/actiontech/dms-ui/pull/696
=> [fix]: delete workbench option and update unit testing

packages/base/src/locale/zh-CN/dmsUserCenter.ts, packages/base/src/page/UserCenter/Drawer/User/UserForm/index.test.tsx, packages/base/src/page/UserCenter/Drawer/User/UserForm/index.tsx
fix:https://github.com/actiontech/dms/issues/503
=> [fix](UserCenter): Add validate rule for user name

packages/base/src/page/System/GlobalSetting/index.tsx, packages/shared/lib/api/base/service/Configuration/index.d.ts, packages/shared/lib/api/base/service/Configuration/index.ts, packages/shared/lib/api/base/service/common.d.ts, packages/shared/lib/api/base/service/common.enum.ts, packages/shared/lib/testUtil/mockApi/base/system/index.ts
issue: https://github.com/actiontech/dms-ee/issues/597#issuecomment-3190840067
全局配置api从sqle替换到dms
=> [feature](System): Migrate the global configuration API to the dms service

packages/shared/lib/api/sqle/service/SqlManage/index.d.ts, packages/shared/lib/api/sqle/service/instance_audit_plan/index.d.ts, packages/shared/lib/api/sqle/service/task/index.d.ts, packages/sqle/src/locale/zh-CN/sqlQuery.ts, packages/sqle/src/page/SqlAnalyze/ManagementConf/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlAnalyze/ManagementConf/index.test.tsx, packages/sqle/src/page/SqlAnalyze/ManagementConf/index.tsx, packages/sqle/src/page/SqlAnalyze/SqlAnalyze/SqlAnalyze.tsx, packages/sqle/src/page/SqlAnalyze/SqlAnalyze/index.tsx, packages/sqle/src/page/SqlAnalyze/SqlAnalyze/test/__snapshots__/SqlAnalyze.test.tsx.snap, packages/sqle/src/page/SqlAnalyze/SqlAnalyze/test/__snapshots__/useSQLExecPlan.test.tsx.snap, packages/sqle/src/page/SqlAnalyze/SqlAnalyze/test/useSQLExecPlan.test.tsx, packages/sqle/src/page/SqlAnalyze/SqlAnalyze/useSQLExecPlan.tsx, packages/sqle/src/page/SqlAnalyze/SqlManage/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlAnalyze/SqlManage/index.test.tsx, packages/sqle/src/page/SqlAnalyze/SqlManage/index.tsx, packages/sqle/src/page/SqlAnalyze/Workflow/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlAnalyze/Workflow/index.test.tsx, packages/sqle/src/page/SqlAnalyze/Workflow/index.tsx
issue: https://github.com/actiontech/sqle-ee/issues/2519
=> [feature](SqlAnalyze): Implement performance data fetch on click

packages/base/src/page/DataSource/components/AddDataSource/__snapshots__/index.test.tsx.snap, packages/shared/lib/components/EditableSelect/EditableSelect.tsx, packages/shared/lib/components/EditableSelect/__tests__/EditableSelect.test.tsx, packages/shared/lib/components/EditableSelect/__tests__/__snapshots__/EditableSelect.test.tsx.snap, packages/shared/lib/components/EditableSelect/style.ts
fix:https://github.com/actiontech/dms-ee/issues/648
=> [fix](EditableSelect): Fix flickering issue caused by input

packages/base/src/hooks/useRecentlySelectedZone/index.ts, packages/base/src/page/AvailabilityZone/AvailabilityZoneWrapper/__tests__/index.test.tsx, packages/base/src/page/AvailabilityZone/AvailabilityZoneWrapper/index.tsx, packages/base/src/page/Nav/SideMenu/__tests__/useRecentlyOpenedProjects.test.ts, packages/base/src/page/Nav/SideMenu/testUtils/data.ts, packages/base/src/page/Nav/SideMenu/useRecentlyOpenedProjects.ts, packages/shared/lib/api/common/ApiBase/index.test.ts, packages/shared/lib/api/common/ApiBase/index.ts, packages/shared/lib/enum/index.ts, packages/shared/lib/features/useUserInfo/index.ts, packages/shared/lib/testUtil/mockApi/baseApi.tsx, packages/shared/lib/testUtil/mockHook/data.tsx
issue:https://github.com/actiontech/dms-ee/issues/670
=> [fix](AvailabilityZone): Availability zone switching and project linkage issues

packages/base/src/page/DataSource/components/AddDataSource/index.test.tsx, packages/base/src/page/DataSource/components/Form/index.tsx
issue:https://github.com/actiontech/dms-ee/issues/583
Cherry pick to 2505.x
=> [fix](DataSource): Test data source connectivity parameter loss

packages/sqle/src/page/SqlExecWorkflow/Detail/components/AuditExecResultPanel/TaskResultList/Common/SqlStatementResultTable/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Detail/components/AuditExecResultPanel/TaskResultList/Common/SqlStatementResultTable/__tests__/index.test.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/AuditExecResultPanel/TaskResultList/Common/SqlStatementResultTable/columns.tsx
fix:https://github.com/actiontech/sqle/issues/3135
=> [fix](SqlExecWorkflow): Show execution results on file mode

packages/sqle/src/locale/zh-CN/versionManagement.ts, packages/sqle/src/page/SqlExecWorkflow/Detail/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Detail/components/PageHeaderExtra/__test__/__snapshots__/index.ce.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Detail/components/PageHeaderExtra/__test__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/SqlExecWorkflow/Detail/components/PageHeaderExtra/__test__/index.test.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/PageHeaderExtra/action.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/PageHeaderExtra/hooks/useWorkflowDetailAction.tsx, packages/sqle/src/page/SqlExecWorkflow/Detail/components/PageHeaderExtra/index.tsx, packages/sqle/src/page/VersionManagement/Detail/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/VersionManagement/Detail/__tests__/index.test.tsx, packages/sqle/src/page/VersionManagement/Detail/components/StageNode/__tests__/__snapshots__/index.test.tsx.snap, packages/sqle/src/page/VersionManagement/Detail/components/StageNode/__tests__/index.test.tsx, packages/sqle/src/page/VersionManagement/Detail/components/StageNode/index.tsx
cherry pick https://github.com/actiontech/dms-ui/pull/741
=> [fix](SqlExecWorkflow): Process optimization after workflow execute failed

packages/base/src/page/Login/index.test.tsx, packages/base/src/page/Login/index.tsx
issue:https://github.com/actiontech/sqle/issues/3142
=> [fix](Login): Navigate to home after logging success

packages/dms-kit/src/features/index.ts, packages/dms-kit/src/index.ts
link https://github.com/actiontech/dms-ui/pull/743
=> [chore]: Export useRecentlySelectedZone in index
