actiontech/dms-ui

packages/base/src/locale/en-US/dmsDataSource.ts
packages/base/src/locale/zh-CN/dmsDataSource.ts
packages/base/src/page/DataSource/DataSourceForm/index.tsx
packages/base/src/page/DataSource/DataSourceForm/index.type.ts

[issue-1945](https://github.com/actiontech/sqle/issues/1945)

[fix](DataSourceForm): supply tips when user attempt to swtich off auditRequired 

---

packages/sqle/src/store/globalRuleTemplate/index.test.ts
packages/sqle/src/store/sqleManagement/index.test.ts
packages/sqle/src/store/sqleManagement/index.tsx

jira: [DMS-820](http://10.186.18.11/jira/browse/DMS-820)

[test](sqle/store): add missing unit test file

---

packages/sqle/src/page/Order/AuditDetail/ScheduleTimeModal/index.test.tsx

jira: [DMS-827](http://10.186.18.11/jira/browse/DMS-827)

upgrade for mock date

---

packages/base/src/page/System/License/__snapshots__/index.test.tsx.snap
packages/base/src/page/System/License/index.data.tsx

issue: [actiontech/dms/issues/174](https://github.com/actiontech/dms/issues/174)

[fix](base/system):upgrade system module license table column width style

---

packages/base/src/page/Account/components/UserEmail.tsx
packages/base/src/page/Account/components/__tests__/UserEmail.test.tsx
packages/base/src/page/Account/components/__tests__/UserPhone.test.tsx
packages/base/src/page/Account/components/__tests__/__snapshots__/UserEmail.test.tsx.snap
packages/base/src/page/Account/components/__tests__/__snapshots__/UserPhone.test.tsx.snap

fix [jira](http://10.186.18.11/jira/browse/DMS-840)

[test]:(Account) Supplementary testing coverage

---

packages/sqle/src/components/BackendForm/AutoCreatedFormItemByApi.tsx
packages/sqle/src/components/BackendForm/__tests__/AutoCreatedFormItemByApi.test.tsx
packages/sqle/src/components/BackendForm/__tests__/__snapshots__/AutoCreatedFormItemByApi.test.tsx.snap
packages/sqle/src/components/BackendForm/index.ts
packages/sqle/src/page/SqlManagementConf/Common/ConfForm/ScanTypesDynamicParams/index.tsx
packages/sqle/src/page/SqlManagementConf/Common/ConfForm/__tests__/ScanTypesDynamicParams.test.tsx

https://github.com/actiontech/sqle/issues/2523
解决: https://github.com/actiontech/sqle/issues/2523#issuecomment-2295788919

[feature]:(ScanTypesDynamicParams) add conditional rendering of form items based on user input

---

packages/base/src/page/DataExportManagement/Create/components/SubmitWorkflow/UpdateInfoDrawer/index.test.tsx
packages/base/src/page/DataExportManagement/Detail/components/ExportDetail/OverviewList/index.test.tsx
packages/base/src/page/Login/index.test.tsx
packages/sqle/src/page/ReportStatistics/EEIndex/component/cardNumberShow/index.test.tsx
packages/sqle/src/page/ReportStatistics/EEIndex/index.test.tsx
packages/sqle/src/page/ReportStatistics/index.test.tsx
packages/sqle/src/page/SqlExecWorkflow/Create/components/AuditResultStep/__tests__/BaseInfoTag.test.tsx
packages/sqle/src/page/SqlExecWorkflow/Detail/components/AuditExecResultPanel/OverviewList/ScheduleTimeModal/__tests__/index.test.tsx
packages/sqle/src/page/SqlExecWorkflow/Detail/components/AuditExecResultPanel/OverviewList/__tests__/index.test.tsx

1. 修复单元测试中部分未生效的 MockDate
2. 补充 MockData.reset()

[fix]:(tests) ineffective mock date in unit tests

---

packages/sqle/src/page/PushRuleConfiguration/components/SqlManagementIssuePush/index.tsx

https://github.com/actiontech/sqle/issues/2527
这个页面的单元测试忘记补了，后面单独加。。

[fix]: set default values when enabling configuration

---

packages/shared/lib/api/sqle/service/common.d.ts
packages/shared/lib/api/sqle/service/common.enum.ts
packages/sqle/src/components/AuditResultMessage/ResultIconRender.tsx
packages/sqle/src/components/AuditResultMessage/style.ts
packages/sqle/src/components/AuditResultMessage/test/ResultIconRender.test.tsx
packages/sqle/src/components/AuditResultMessage/test/__snapshots__/ResultIconRender.test.tsx.snap
packages/sqle/src/page/PipelineConfiguration/Update/index.tsx
packages/sqle/src/page/SqlManagement/component/SQLEEIndex/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/SqlManagement/component/SQLEEIndex/column.tsx
packages/sqle/src/page/SqlManagementConf/Detail/ScanTypeSqlCollection/__tests__/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/SqlManagementConf/Detail/ScanTypeSqlCollection/indx.tsx
packages/sqle/src/page/SqlManagementConf/Detail/ScanTypeSqlCollection/style.ts
packages/sqle/src/testUtils/mockApi/instanceAuditPlan/data.ts
packages/sqle/src/testUtils/mockApi/sqlManage/data.ts

issue: https://github.com/actiontech/sqle/issues/2572

[fix]: SQL Management and scanning tasks add auditing status

---

packages/sqle/src/page/SqlAudit/List/index.test.tsx
packages/sqle/src/page/SqlAudit/List/index.tsx
packages/sqle/src/page/SqlManagement/component/SQLEEIndex/index.test.tsx
packages/sqle/src/page/SqlManagement/component/SQLEEIndex/index.tsx
packages/sqle/src/page/SqlManagementConf/Detail/ScanTypeSqlCollection/__tests__/index.test.tsx
packages/sqle/src/page/SqlManagementConf/Detail/ScanTypeSqlCollection/indx.tsx

issue: https://github.com/actiontech/sqle/issues/2572
快速审核、SQL管控、SQL管控配置-任务详情列表 当sql处理‘审核中’状态时，自动刷新列表数据

[feature](SqlAudit&SqlManagement&SqlManagementConf): Automatic refresh logic

---

packages/shared/lib/api/sqle/service/common.d.ts
packages/sqle/src/page/SqlExecWorkflow/Detail/__tests__/index.test.tsx
packages/sqle/src/page/SqlExecWorkflow/Detail/hooks/useGenerateWorkflowStepsProps.ts
packages/sqle/src/page/VersionManagement/Detail/Modal/AssociateWorkflowModal/WorkflowTableField/index.tsx
packages/sqle/src/page/VersionManagement/Detail/Modal/OfflineExecModal/index.tsx
packages/sqle/src/page/VersionManagement/Detail/Modal/ReleaseModal/hooks/useTestConnection.tsx
packages/sqle/src/page/VersionManagement/Detail/Modal/ReleaseModal/index.tsx

- 线下执行功能联调
link  https://github.com/actiontech/dms-ui/pull/426

[feature]: Offline Execute workflow

---

packages/base/src/App.tsx
packages/base/src/page/DataSourceManagement/index.tsx
packages/base/src/page/Nav/SideMenu/MenuList/index.tsx
packages/base/src/page/Nav/SideMenu/MenuList/index.type.ts
packages/base/src/page/Nav/SideMenu/MenuList/menus/common.ts
packages/base/src/page/Nav/SideMenu/MenuList/menus/index.type.ts
packages/base/src/page/Nav/SideMenu/MenuList/menus/menu.data.dms.tsx
packages/base/src/page/Nav/SideMenu/MenuList/menus/menu.data.tsx
packages/base/src/page/Nav/SideMenu/MenuList/menus/sqle.tsx
packages/base/src/page/Nav/SideMenu/UserMenu/components/ContextMenu/index.tsx
packages/base/src/page/Nav/SideMenu/UserMenu/components/ContextMenu/index.type.ts
packages/base/src/page/Nav/SideMenu/UserMenu/components/GlobalSetting.tsx
packages/base/src/page/Nav/SideMenu/UserMenu/index.tsx
packages/base/src/page/Nav/SideMenu/UserMenu/index.type.ts
packages/base/src/page/Nav/SideMenu/index.ce.tsx
packages/base/src/page/Nav/SideMenu/index.tsx
packages/base/src/router/router.base.tsx
packages/shared/lib/enum/index.ts
packages/shared/lib/global/index.ts
packages/shared/lib/global/useCurrentPermission/index.tsx
packages/shared/lib/global/useCurrentUser/index.ts
packages/shared/lib/global/usePermission/index.ts
packages/shared/lib/global/usePermission/permissionManifest.ts
packages/shared/lib/global/usePermission/permissions.ts
packages/shared/lib/global/usePermission/usePermission.ts
packages/shared/lib/types/common.type.ts
packages/sqle/src/router/config.tsx

1.  创建权限集合
2. 创建权限清单集合
3. 创建 usePermission, 实现处理页面级别相关权限的函数
4. 重构所有页面级别相关的权限，包括左侧菜单入口、全局设置相关菜单入口、路由
暂时先跳过 ci 检查，后续会新开 pr 处理 checker 错误以及单元测试

[feature]: Refactor page-level permission handling [skip ci]

---

packages/base/src/page/DataSource/components/List/columns.tsx
packages/base/src/page/DataSource/components/List/index.tsx
packages/shared/lib/components/ActiontechTable/hooks/useTableAction.tsx
packages/shared/lib/components/ActiontechTable/index.type.ts
packages/shared/lib/global/useCurrentPermission/index.tsx
packages/shared/lib/global/usePermission/index.ts
packages/shared/lib/global/usePermission/index.type.ts
packages/shared/lib/global/usePermission/permissionManifest.ts
packages/shared/lib/global/usePermission/permissions.ts
packages/shared/lib/global/usePermission/usePermission.ts
packages/shared/lib/global/useUserOperationPermission/index.ts

重构了数据源列表 操作列的权限相关的代码。
主要包含了以下几种情况：
1. 前端自定义角色控制权限
2. 是否为当前项目管理员
3. 当前项目是否冻结
4. 当前用户在当前项目内对当前数据源是否拥有某些权限。权限设置路径：成员与权限页面添加成员时设置在角色中心预设置的角色。

[feature](usePermission、DataSource): Refactor permissions for table operation column buttons  [skip ci]

---

packages/sqle/src/page/SqlManagementConf/List/column.tsx
packages/sqle/src/page/SqlManagementConf/List/index.tsx

https://github.com/actiontech/sqle/issues/2599
相关 issue：https://github.com/actiontech/sqle/issues/2672
临时调整创建扫描任务按钮的权限，由于已通过创建页面获取数据源的数据做了权限筛选，故这里只需要项目未冻结时，便能进入创建页面。
优先级：高

[fix]: Adjust button permissions for enhanced access control

---

packages/sqle/src/page/SqlManagementConf/Detail/ScanTypeSqlCollection/__tests__/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/SqlManagementConf/Detail/ScanTypeSqlCollection/indx.tsx

Reverts actiontech/dms-ui#489
回退原因：改 release 代码得发小版本。但是这个影响没那么大，主要是浙农信要用，后端直接在dms-ui切了个分支给他们用，release就不变了。

Revert "[fix](SqlManagementConf): Time type judgment"

---

packages/shared/lib/api/sqle/service/common.d.ts
packages/shared/lib/api/sqle/service/common.enum.ts
packages/shared/lib/api/sqle/service/sql_audit_record/index.d.ts
packages/shared/lib/api/sqle/service/sql_audit_record/index.ts
packages/shared/lib/api/sqle/service/task/index.d.ts
packages/shared/lib/api/sqle/service/task/index.ts
packages/shared/lib/api/sqle/service/workflow/index.d.ts
packages/shared/lib/api/sqle/service/workflow/index.enum.ts
packages/shared/lib/api/sqle/service/workflow/index.ts
packages/sqle/src/locale/zh-CN/sqlAudit.ts
packages/sqle/src/page/SqlAudit/Create/SQLInfoForm/SQLInfoFormItem.tsx
packages/sqle/src/page/SqlAudit/Create/SQLInfoForm/index.type.ts
packages/sqle/src/page/SqlAudit/Create/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/SqlAudit/Create/index.test.tsx
packages/sqle/src/page/SqlAudit/Create/index.tsx

https://github.com/actiontech/sqle/issues/2742

[feature]: Support for selecting audit rule templates in static audit

---

packages/base/src/page/DataSource/components/List/ConnectionResultColumn.tsx
packages/shared/lib/components/ActiontechTable/hooks/useCustomFilter.tsx
packages/shared/lib/components/ActiontechTable/hooks/useTableFilterContainer.tsx
packages/shared/lib/components/ActiontechTable/hooks/useTableRequestParams.tsx
packages/shared/lib/components/ActiontechTable/index.type.ts
packages/sqle/src/page/PluginAudit/List/columns.tsx
packages/sqle/src/page/SqlManagementException/List/column.tsx
packages/sqle/src/page/VersionManagement/List/column.tsx

修复 ActiontechTable - updateTableFilterInfo 函数类型异常

fix: Resolve type exception in updateTableFilterInfo function

---

packages/sqle/src/components/RuleDetail/__snapshots__/index.test.tsx.snap
packages/sqle/src/components/RuleList/RuleList.tsx
packages/sqle/src/components/RuleList/test/RuleList.ce.test.tsx
packages/sqle/src/components/RuleList/test/RuleList.test.tsx
packages/sqle/src/components/RuleList/test/__snapshots__/RuleList.test.tsx.snap
packages/sqle/src/page/CustomRule/CustomRuleList/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/GlobalRuleTemplate/CreateRuleTemplate/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/GlobalRuleTemplate/ImportRuleTemplate/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/GlobalRuleTemplate/RuleTemplateDetail/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/GlobalRuleTemplate/UpdateRuleTemplate/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/Rule/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/RuleManager/__tests__/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/RuleTemplate/CreateRuleTemplate/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/RuleTemplate/ImportRuleTemplate/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/RuleTemplate/RuleTemplateDetail/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/RuleTemplate/RuleTemplateForm/RuleSelect/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/RuleTemplate/RuleTemplateForm/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/RuleTemplate/UpdateRuleTemplate/__snapshots__/index.test.tsx.snap

Reverts actiontech/dms-ui#510
link https://github.com/actiontech/dms-ui-ee/pull/315

Revert "Fix/issue 2777 2"

---

packages/base/src/page/Nav/SideMenu/MenuList/index.tsx

[fix](Nav): Fix menu children errors

---

packages/sqle/src/components/AuditResultMessage/ResultIconRender.tsx
packages/sqle/src/page/SqlManagementConf/Detail/ScanTypeSqlCollection/__tests__/index.test.tsx
packages/sqle/src/page/SqlManagementConf/Detail/ScanTypeSqlCollection/indx.tsx
packages/sqle/src/testUtils/mockApi/instanceAuditPlan/data.ts

issue: https://github.com/actiontech/sqle/issues/2814

[fix](SqlManagementConf): Add audit status field

---

packages/base/src/page/Member/Modal/Member/MemberForm.tsx
packages/base/src/page/Member/Modal/Member/__tests__/AddMember.test.tsx
packages/base/src/page/Member/Modal/Member/__tests__/UpdateMember.test.tsx
packages/base/src/page/Member/Modal/Member/__tests__/__snapshots__/AddMember.test.tsx.snap
packages/shared/lib/api/base/service/User/index.d.ts

解决浙江农信现场用户数量上万条导致接口加载时间过长的问题。
先临时解决 添加成员处 的问题，其他获取用户 tips 的接口的处理方案待定。
优先级：高

[feature]:(AddMember) add remote search for username tips

---

packages/sqle/src/page/SqlAudit/Create/SQLInfoForm/SQLInfoFormItem.tsx
packages/sqle/src/page/SqlAudit/Create/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/SqlAudit/Create/index.test.tsx

fix issue: https://github.com/actiontech/sqle/issues/2846
静态审核时全局规则模板选择范围由默认规则模板调整为当前数据源类型所对应的所有规则模板

[fix]: (SqlAudit) adjust global rule template selection for static auditing

---

packages/base/src/page/CloudBeaver/List/column.tsx
packages/base/src/page/DataExportManagement/Common/AuditResultList/Table/column.tsx
packages/base/src/page/DataExportManagement/Create/hooks/__tests__/useCheckTaskAuditRuleExceptionStatus.test.ts
packages/base/src/page/DataExportManagement/Create/hooks/useCheckTaskAuditRuleExceptionStatus.ts
packages/shared/lib/api/base/service/common.d.ts
packages/shared/lib/api/sqle/service/common.d.ts
packages/sqle/src/components/AuditResultMessage/ResultIconRender.tsx
packages/sqle/src/components/AuditResultMessage/__tests__/ResultIconRender.test.tsx
packages/sqle/src/components/AuditResultMessage/index.type.ts
packages/sqle/src/components/ReportDrawer/__tests__/index.test.tsx
packages/sqle/src/components/ReportDrawer/index.tsx
packages/sqle/src/page/PluginAudit/List/columns.tsx
packages/sqle/src/page/SqlExecWorkflow/Common/AuditResultList/Table/column.tsx
packages/sqle/src/page/SqlExecWorkflow/Create/hooks/useCheckTaskAuditRuleExceptionStatus.ts
packages/sqle/src/page/SqlExecWorkflow/Detail/components/AuditExecResultPanel/TaskResultList/Common/SqlStatementResultTable/columns.tsx
packages/sqle/src/page/SqlManagement/component/SQLEEIndex/column.tsx
packages/sqle/src/page/SqlManagementConf/Detail/ScanTypeSqlCollection/indx.tsx
packages/sqle/src/testUtils/mockApi/task/data.ts

https://github.com/actiontech/sqle/issues/2868
新增  execution_failed 字段用来判断当前审核是否出现异常

[fix]: update  code to reflect backend field changes

---

package.json
packages/shared/lib/utils/Common.ts
packages/shared/lib/utils/__tests__/Common.test.ts
packages/sqle/src/page/PushRuleConfiguration/__snapshots__/index.ce.test.tsx.snap
packages/sqle/src/page/PushRuleConfiguration/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/PushRuleConfiguration/components/SqlManagementIssuePush/__tests__/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/PushRuleConfiguration/components/WorkflowUpdateNotifier/__tests__/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/WorkflowTemplate/WorkflowTemplateDetail/components/WorkflowTemplateAuthInfo/index.tsx
pnpm-lock.yaml

[chore]: Remove moment package

---

packages/sqle/src/page/RuleTemplate/RuleTemplateList/index.test.tsx
packages/sqle/src/page/RuleTemplate/RuleTemplateList/index.tsx

fix issue: https://github.com/actiontech/sqle/issues/2932

[feature](RuleTemplate): add permission check for global rule template

---

packages/sqle/src/locale/zh-CN/dataSourceComparison.ts
packages/sqle/src/page/DataSourceComparison/ComparisonEntry/__tests__/index.test.tsx
packages/sqle/src/page/DataSourceComparison/ComparisonEntry/index.tsx
packages/sqle/src/page/DataSourceComparison/ComparisonEntry/utils/TreeNode.tsx

https://github.com/actiontech/sqle-ee/issues/2243
1. 当对比结果没有差异是禁用仅看差异按钮
2. 修复生成变更SQL参数异常问题（当全选树节点时额外包含了 parent 节点的value，需要过滤掉）

[fix]:(SQLE/DataSourceComparison) disable diff-only button when no differences found and fix SQL parameter generation issue

---

packages/shared/lib/types/common.type.ts
packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/SqlStatementFormItem/__tests__/SqlFormatterAndSubmitter.test.tsx
packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/SqlStatementFormItem/__tests__/index.test.tsx
packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/SqlStatementFormItem/components/SqlFormatterAndSubmitter.tsx
packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/SqlStatementFormItem/components/index.type.ts
packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/SqlStatementFormItem/index.tsx
packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/SqlStatementFormItem/index.type.ts
packages/sqle/src/page/SqlExecWorkflow/Common/SqlStatementFormController/index.tsx

fix: https://github.com/actiontech/sqle-ee/issues/2293

[fix](SqlExecWorkflow): Optimize the verification of audit forms

---

packages/shared/lib/api/common/authInvalid/index.test.tsx
packages/shared/lib/api/common/authInvalid/index.ts

fix issue: https://github.com/actiontech/sqle-ee/issues/2361
修复当前 path 为 login ， token 过期并且 refresh token 报错的情况下未清空 token 等数据的问题

[fix](auth): not redirect to login and clean  user when current path is login

---

packages/sqle/src/page/PipelineConfiguration/List/__tests__/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/PipelineConfiguration/List/column.tsx
packages/sqle/src/page/PipelineConfiguration/List/index.tsx

fix:https://github.com/actiontech/sqle/issues/3085

[fix](PipelineConfiguration): Adjust list styles

---

packages/sqle/src/page/SqlExecWorkflow/Detail/components/AuditExecResultPanel/TaskResultList/Common/SqlStatementResultTable/__tests__/__snapshots__/index.test.tsx.snap
packages/sqle/src/page/SqlExecWorkflow/Detail/components/AuditExecResultPanel/TaskResultList/Common/SqlStatementResultTable/__tests__/index.test.tsx
packages/sqle/src/page/SqlExecWorkflow/Detail/components/AuditExecResultPanel/TaskResultList/Common/SqlStatementResultTable/columns.tsx

issue:https://github.com/actiontech/sqle/issues/3135
Cherry pick to 2505.x

[fix](SqlExecWorkflow): Show execution results on file mode
